import { capability, id, now } from './core.js';
import { store } from './store.js';
import { hasD1 } from './db.js';
import { learningAdjustedRate } from './agent-learning.js';

export const AGENT_STATES = ['registered','available','assigned','working','verifying','completed','blocked','escalated','offline'];
// Built-in agents get a deterministic id derived from their name so re-seeding is an
// UPSERT of the same row instead of inserting a fresh duplicate copy on every cold start.
export function builtinAgentId(name){return 'agent-builtin-'+String(name??'agent').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
export function registerAgent({ name, role, department = 'General', capabilities = [], tools = [], metadata = {}, id: requestedId }) { const agent=store.put('agents',{id:requestedId??id('agent'),name,role,department,capabilities,tools,state:'available',heartbeatAt:now(),metadata}); store.addEvent('agent.registered',agent); return agent; }
export function updateAgent(idValue, patch) { const current=store.get('agents',idValue); if(!current)return null; const next=store.put('agents',{...current,...patch,id:current.id}); store.addEvent('agent.updated',next); return next; }
function agentDedupeScore(agent){
  const metadata=agent?.metadata??{};
  let score=Object.keys(metadata.learning??{}).length*10+Object.keys(metadata.skillTree??{}).length*2+Math.max(0,Number(metadata.successRate??0))*5;
  if(agent?.state==='available')score+=3;
  if(agent?.currentTaskId)score-=10;
  const timestamp=Date.parse(agent?.updatedAt??agent?.heartbeatAt??0);
  return Number.isFinite(timestamp)?score+Math.min(10,timestamp/1e12):score;
}
export function dedupeAgentList(agents){
  const byName=new Map();
  for(const agent of(Array.isArray(agents)?agents:[])){
    if(!agent||typeof agent!=='object')continue;
    const name=String(agent.name??'').trim().toLowerCase();
    const key=name||`id:${String(agent.id??'')}`;
    const current=byName.get(key);
    if(!current||agentDedupeScore(agent)>agentDedupeScore(current))byName.set(key,agent);
  }
  return [...byName.values()].sort((a,b)=>String(a.name??a.id??'').localeCompare(String(b.name??b.id??'')));
}
export function listAgents(){return dedupeAgentList(store.list('agents'));}
export function recordAgentOutcome(agentId,outcome={}){const agent=store.get('agents',agentId);if(!agent)return null;const metadata={...(agent.metadata??{})};const total=Math.max(0,Number(metadata.outcomeCount??0));const successes=Math.max(0,Number(metadata.successCount??0));const success=outcome.success===true;const nextTotal=total+1;const nextSuccesses=successes+(success?1:0);metadata.outcomeCount=nextTotal;metadata.successCount=nextSuccesses;metadata.failureCount=Math.max(0,nextTotal-nextSuccesses);metadata.successRate=nextSuccesses/nextTotal;metadata.lastOutcomeAt=now();metadata.lastOutcome=success?'success':'failure';metadata.reliabilityScore=Math.round(metadata.successRate*100);if(!success){metadata.consecutiveFailures=Math.max(0,Number(metadata.consecutiveFailures??0))+1;}else{metadata.consecutiveFailures=0;delete metadata.cooldownUntil;}if(metadata.consecutiveFailures>=3){metadata.cooldownUntil=Date.now()+300000;}return updateAgent(agentId,{metadata});}
function contextualRate(agent, requiredCapabilities=[]){const key=[...new Set(requiredCapabilities)].sort().join('|')||'general';return learningAdjustedRate(agent.metadata?.learning?.[key]);}
function workloadPenalty(agent,options={}){const active=Number(agent.metadata?.activeTaskCount??0);const max=Number(agent.metadata?.maxConcurrentTasks??1);if(options.ignoreWorkload)return 0;if(active>=max)return -100;return Math.max(-30,-active*10);}
function reliabilityPenalty(agent,options={}){const metadata=agent.metadata??{};if(metadata.cooldownUntil&&Date.now()<Number(metadata.cooldownUntil)){return options.allowCooldownFallback?-1000:-Infinity;}const failures=Number(metadata.consecutiveFailures??0);return failures>0?-Math.min(35,failures*8):0;}
function toolMatch(agent,requiredTools=[]){const required=[...new Set(requiredTools.filter(Boolean))];const available=new Set(agent.tools??[]);const matched=required.filter(tool=>available.has(tool));const missing=required.filter(tool=>!available.has(tool));return{matched,missing,score:matched.length===required.length?Math.min(30,matched.length*10):0};}
export function scoreAgent(agent,requiredCapabilities=[],options={}){const required=[...new Set(requiredCapabilities)];const caps=new Set(agent.capabilities??[]);const matched=required.filter(c=>caps.has(c));if(required.length&&matched.length!==required.length)return -Infinity;const tools=toolMatch(agent,options.requiredTools??[]);const planningTask=required.includes('planning')||required.includes('product-planning');if(tools.missing.length&&options.requireAllTools!==false&&!planningTask)return -Infinity;let score=matched.length*100+Math.min((agent.capabilities??[]).length,20)+tools.score;if(options.department&&agent.department===options.department)score+=25;if(options.preferredRole&&agent.role===options.preferredRole)score+=15;if(agent.state==='available')score+=20;const metadata=agent.metadata??{};if(Number.isFinite(metadata.successRate))score+=Math.max(0,Math.min(20,metadata.successRate*20));if(Number.isFinite(metadata.reliabilityScore))score+=Math.max(0,Math.min(20,metadata.reliabilityScore*.2));if(Number.isFinite(metadata.priority))score+=metadata.priority;const rate=contextualRate(agent,required);if(rate!==null)score+=Math.max(0,Math.min(40,rate*40));score+=reliabilityPenalty(agent,options);score+=workloadPenalty(agent,options);return score;}
function recoverable(agent){if(agent.state==='available')return true;const taskId=agent.currentTaskId;if(!taskId)return false;const task=store.get('tasks',taskId);if(!task)return false;const running=store.list('runs').some(run=>{if(run.taskId!==taskId||run.state!=='running')return false;const started=Date.parse(run.startedAt??'');if(!Number.isFinite(started))return true;return Date.now()-started<10*60*1000;});return !running;}
export function selectAgents(requiredCapabilities=[],department=null,options={}){return listAgents().filter(a=>(a.state==='available'||recoverable(a))&&(!department||a.department===department)).map(agent=>({agent,score:scoreAgent(agent,requiredCapabilities,{...options,department})})).filter(x=>Number.isFinite(x.score)).sort((a,b)=>b.score-a.score||String(a.agent.id).localeCompare(String(b.agent.id))).map(x=>x.agent);}
export function selectBestAgent(requiredCapabilities=[],options={}){return selectAgents(requiredCapabilities,options.department??null,options)[0]??null;}

const DEFAULT_AGENTS=[['SK Executive','Executive','Executive',['planning','governance','delegation','strategy'],[]],['Research Agent','Research','Research',['research','analysis','web-search','investigation'],['web.search','web.fetch']],['Product Agent','Product','Business',['requirements','product-planning','planning','strategy','market-analysis'],['planning.execute','documentation.generate']],['Planning Agent','Planner','Planning',['product-planning','planning','architecture','roadmap'],['planning.execute','documentation.generate']],['Frontend Agent','Engineer','Engineering',['frontend','javascript','ui','react','vue','css','html','responsive'],['code.execute','test.run','ui.design','file.write']],['Backend Agent','Engineer','Engineering',['backend','api','javascript','node','python','rest','graphql'],['code.execute','test.run','database.query','api.test']],['Database Agent','Engineer','Engineering',['database','schema','sql','migration','data-modeling','optimization'],['database.query','database.migrate','data.analyze']],['Security Agent','Reviewer','Security',['security','audit','vulnerability-scan','compliance','penetration-testing'],['security.scan','security.audit']],['QA Agent','Tester','Quality',['testing','verification','automation','regression','performance'],['test.run','code.execute','api.test']],['DevOps Agent','Engineer','Infrastructure',['deployment','ci-cd','infrastructure','devops','cloud','docker','kubernetes'],['deploy.execute','deploy.preview','monitor.metrics']],['Mobile Agent','Engineer','Engineering',['mobile','android','ios','swift','kotlin','flutter','react-native','pwa'],['mobile.build','mobile.preview','code.execute','test.run']],['Desktop Agent','Engineer','Engineering',['desktop','windows','macos','linux','electron','tauri'],['code.execute','test.run','file.write']],['AI/ML Agent','Engineer','Intelligence',['machine-learning','neural-networks','ai','data-science','deep-learning','nlp'],['ai.train','ai.infer','code.execute','data.analyze']],['Data Agent','Engineer','Intelligence',['data-analysis','visualization','charts','analytics','etl','data-pipeline'],['data.analyze','data.transform','database.query']],['Creative Agent','Designer','Design',['design','ui-ux','graphics','creative','branding','animation'],['ui.design','media.generate','file.write']],['API Agent','Engineer','Engineering',['api','rest','graphql','websocket','microservices','documentation'],['api.test','api.document','code.execute','test.run']],['PDF Agent','Engineer','Documents',['pdf','document','report','invoice','certificate','resume'],['code.execute','documentation.generate']],['Native Agent','Engineer','Engineering',['native','kotlin','swift','react-native','flutter','platform-specific'],['mobile.build','mobile.preview','code.execute','test.run']]];
function activeTaskOwnedBy(agent){const taskId=agent?.currentTaskId;if(!taskId)return false;const task=store.get('tasks',taskId);if(!task||task.agentId!==agent.id||!['assigned','working','verifying'].includes(task.state))return false;return store.list('runs').some(run=>{if(run.taskId!==taskId||run.state!=='running')return false;const started=Date.parse(run.startedAt??'');if(!Number.isFinite(started))return true;return Date.now()-started<10*60*1000;});}
const SEED_HEARTBEAT_INTERVAL_MS=5*60*1000;
function sameSet(a,b){const x=a??[],y=b??[];return x.length===y.length&&x.every(v=>y.includes(v));}
// seedAgents runs on every isolate start and on every pipeline-gate creation. Patching
// all ~19 built-in agents unconditionally wrote a row + an event per agent (~38 D1 writes)
// per call, and with a cold isolate every minute that alone crossed the free-tier
// 100K rows_written/day budget. Heartbeat-only refreshes are therefore throttled and quiet.
export function seedAgents(){const existingByName=new Map(listAgents().map(agent=>[agent.name,agent]));const heartbeatFloor=Date.now()-SEED_HEARTBEAT_INTERVAL_MS;for(const [name,role,department,caps,tools] of DEFAULT_AGENTS){const current=existingByName.get(name);if(!current){const seeded={id:builtinAgentId(name),name,role,department,capabilities:caps,tools,state:'available',heartbeatAt:now(),metadata:{}};if(!store.hydrated&&hasD1(store.env)){const bucket=store.data.get('agents')??new Map();if(!bucket.has(seeded.id)){bucket.set(seeded.id,{...seeded,createdAt:now(),updatedAt:now()});store.data.set('agents',bucket);}}else registerAgent(seeded);continue;}const mergedCapabilities=[...new Set([...(current.capabilities??[]),...caps])];const mergedTools=[...new Set([...(current.tools??[]),...tools])];const ownsActiveTask=activeTaskOwnedBy(current);const stateStale=!ownsActiveTask&&(current.state!=='available'||current.currentTaskId!=null);if(sameSet(mergedCapabilities,current.capabilities)&&sameSet(mergedTools,current.tools)&&!stateStale){const heartbeat=Date.parse(current.heartbeatAt??current.updatedAt??0);if(Number.isFinite(heartbeat)&&heartbeat>=heartbeatFloor)continue;const quiet={...current,heartbeatAt:now(),updatedAt:now(),id:current.id};if(!store.hydrated&&hasD1(store.env)){const bucket=store.data.get('agents')??new Map();bucket.set(current.id,quiet);store.data.set('agents',bucket);}else store.put('agents',quiet);continue;}const patch={capabilities:mergedCapabilities,tools:mergedTools,heartbeatAt:now()};if(!ownsActiveTask){patch.state='available';patch.currentTaskId=null;}if(!store.hydrated&&hasD1(store.env)){const bucket=store.data.get('agents')??new Map();bucket.set(current.id,{...current,...patch});store.data.set('agents',bucket);}else updateAgent(current.id,patch);}return listAgents();}
export { capability };