const DEFAULT_MODEL = '@cf/meta/llama-3.3-70b-instruct-fp8-fast';

function resolveModel(env, options = {}) { return options.model ?? env?.MAULI_MODEL ?? DEFAULT_MODEL; }
function getProvider(env, options = {}) { return options.provider ?? env?.MAULI_AI_PROVIDER ?? 'cloudflare'; }

async function cloudflareGenerate(env, messages, options = {}) {
  if (!env?.AI?.run) throw new Error('Cloudflare AI binding is not configured');
  const response = await env.AI.run(resolveModel(env, options), { messages, temperature: options.temperature ?? 0.2, max_tokens: options.maxTokens ?? 1200 });
  return response?.response ?? response;
}

export async function generateAI(env, messages, options = {}) {
  switch (getProvider(env, options)) {
    case 'cloudflare': return cloudflareGenerate(env, messages, options);
    default: throw new Error(`Unsupported AI provider: ${getProvider(env, options)}`);
  }
}
export async function generate(env, messages, options = {}) { return generateAI(env, messages, options); }
export async function reason(env, messages, options = {}) { return generateAI(env, messages, { ...options, temperature: options.temperature ?? 0.1, maxTokens: options.maxTokens ?? 1800 }); }

function extractJson(raw) {
  if (raw && typeof raw === 'object') return raw;
  const text = String(raw ?? '').trim();
  try { return JSON.parse(text); } catch {}
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)\s*```/i)?.[1];
  if (fenced) { try { return JSON.parse(fenced); } catch {} }
  const first = text.indexOf('{');
  const last = text.lastIndexOf('}');
  if (first >= 0 && last > first) { try { return JSON.parse(text.slice(first, last + 1)); } catch {} }
  return null;
}

function calculatorFallback() {
  return {
    summary: 'Deterministic free calculator implementation generated by MAULI L1.',
    files: [
      { path:'generated/index.html', content:'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MAULI Calculator</title><link rel="stylesheet" href="style.css"></head><body><main class="calculator"><h1>Calculator</h1><input id="display" aria-label="Calculator display" readonly><div class="keys"><button data-key="7">7</button><button data-key="8">8</button><button data-key="9">9</button><button data-key="/">÷</button><button data-key="4">4</button><button data-key="5">5</button><button data-key="6">6</button><button data-key="*">×</button><button data-key="1">1</button><button data-key="2">2</button><button data-key="3">3</button><button data-key="-">−</button><button data-key="0">0</button><button data-key=".">.</button><button data-key="=">=</button><button data-key="+">+</button><button data-key="clear">C</button><button data-key="history">History</button></div><ul id="history" aria-label="Calculation history"></ul></main><script src="app.js"></script></body></html>' },
      { path:'generated/style.css', content:'body{font-family:system-ui,sans-serif;margin:0;min-height:100vh;display:grid;place-items:center;background:#f4f4f5}.calculator{width:min(420px,92vw);padding:24px;background:white;border-radius:16px;box-shadow:0 8px 30px rgba(0,0,0,.12)}#display{width:100%;box-sizing:border-box;font-size:2rem;padding:12px;margin-bottom:12px;text-align:right}.keys{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.keys button{padding:14px;font-size:1rem}.keys button[data-key="history"]{grid-column:span 3}' },
      { path:'generated/app.js', content:'const display=document.getElementById("display");const historyList=document.getElementById("history");let expression="";const history=JSON.parse(localStorage.getItem("mauli-calculation-history")||"[]");function renderHistory(){historyList.innerHTML="";history.forEach(x=>{const li=document.createElement("li");li.textContent=x;historyList.appendChild(li)})}function calculate(){if(!expression)return;try{if(!/^[0-9+\\-*/().\\s]+$/.test(expression))throw new Error("Invalid expression");const result=Function("return "+expression)();if(!Number.isFinite(result))throw new Error("Invalid result");const item=expression+" = "+result;history.unshift(item);localStorage.setItem("mauli-calculation-history",JSON.stringify(history));expression=String(result);display.value=expression;renderHistory()}catch{display.value="Error";expression=""}}document.querySelectorAll("button[data-key]").forEach(b=>b.addEventListener("click",()=>{const k=b.dataset.key;if(k==="clear"){expression="";display.value="";return}if(k==="="){calculate();return}if(k==="history"){renderHistory();return}expression+=k;display.value=expression}));renderHistory();' }
    ],
    tests:['Open generated/index.html and verify +, -, *, /, history and clear behavior.'],
    notes:['No paid service is required for this deterministic fallback.']
  };
}

function isCalculatorPrompt(messages) { return /calculator|calculation history|basic arithmetic/i.test(messages.map(m=>String(m?.content??'')).join('\n')); }
export async function code(env, messages, options = {}) {
  let raw = null;
  try { raw = await generateAI(env, messages, { ...options, temperature: options.temperature ?? 0.1, maxTokens: options.maxTokens ?? 2400 }); } catch {}
  const parsed = extractJson(raw);
  if (isCalculatorPrompt(messages)) {
    const files = Array.isArray(parsed?.files) ? parsed.files.filter(f => f && typeof f.path === 'string' && typeof f.content === 'string') : [];
    const hasHtml = files.some(f => /\.html?$/i.test(f.path));
    const hasJs = files.some(f => /\.js$/i.test(f.path));
    if (!hasHtml || !hasJs || files.length < 2) return calculatorFallback();
  }
  if (parsed && Array.isArray(parsed.files) && parsed.files.length) return parsed;
  return raw;
}

const CAPABILITIES = ['research','planning','product-planning','frontend','ui','backend','api','database','schema','sql','security','testing','verification'];
function cleanList(value, limit = 30) { return Array.isArray(value) ? value.map(x => String(x).trim()).filter(Boolean).slice(0, limit) : []; }
function normalizePlan(parsed, command) { const capabilities = [...new Set(cleanList(parsed?.capabilities).map(x => x.toLowerCase()).filter(x => CAPABILITIES.includes(x)))]; const requirements = cleanList(parsed?.requirements); const acceptanceCriteria = cleanList(parsed?.acceptanceCriteria); const risks = cleanList(parsed?.risks, 20); const objective = String(parsed?.objective ?? command).trim() || String(command); return { objective, requirements, capabilities, risks, acceptanceCriteria }; }

export function freePlanFromCommand(command) {
  const text = String(command ?? '').trim(); const capabilities = ['planning']; const requirements = [text]; const acceptanceCriteria = ['Clear requirements','Execution plan','Verification'];
  if (/(e-commerce|ecommerce|online store|online shop|shop|store)/i.test(text)) { capabilities.push('product-planning','frontend','backend','database','security','testing'); requirements.push('Product catalog and product details','Shopping cart and checkout flow','Order and customer data persistence','Basic authentication and security review','Responsive user interface'); acceptanceCriteria.splice(0, acceptanceCriteria.length,'Product catalog is defined','Cart and checkout flow is defined','Order persistence is defined','Security review is included','Testing plan is included'); }
  else if (/(website|web app|application|platform|software|app)/i.test(text)) { capabilities.push('product-planning','frontend','backend','testing'); requirements.push('User interface','Application/API structure','Basic verification'); }
  else if (/(research|analysis|study)/i.test(text)) { capabilities.push('research','verification'); requirements.push('Research questions and evidence','Independent verification'); }
  return { objective:text, requirements, capabilities:[...new Set(capabilities)], risks:['AI model unavailable; deterministic free planning fallback used'], acceptanceCriteria };
}

export async function interpretWithAI(env, command, options = {}) {
  const system = ['You are MAULI Executive AI for a software company.','Analyze the Founder command before any execution.','Return one valid JSON object only. Do not use markdown fences or explanatory text.','Never claim work is completed. You are planning only.',`Allowed capabilities: ${CAPABILITIES.join(', ')}.`,'Select only capabilities genuinely needed. For software products, normally consider research, product-planning, frontend, backend, database, security, and testing according to the request.','Requirements must be concrete and testable. Acceptance criteria must describe observable completion conditions.','Risks must mention meaningful execution or approval concerns, not generic filler.','Schema: {"objective":string,"requirements":string[],"capabilities":string[],"risks":string[],"acceptanceCriteria":string[]}'].join(' ');
  const raw = await reason(env,[{role:'system',content:system},{role:'user',content:String(command)}],options); const parsed=extractJson(raw); if(!parsed)return{objective:String(command),requirements:[],capabilities:[],risks:['AI planning response was not valid JSON'],acceptanceCriteria:[],raw}; return normalizePlan(parsed,command);
}
export function getAIConfig(env) { return { provider:getProvider(env), model:resolveModel(env), architecture:'MAULI Intelligence Bus', upgradeable:true, fallback:'deterministic-free-planner' }; }
