import { id, now } from './core.js';
import { store } from './store.js';
import { createProject, addTaskToProject } from './projects.js';
import { seedAgents, selectAgents, registerAgent, updateAgent } from './agents.js';
import { remember } from './memory.js';
import { interpretWithAI, freePlanFromCommand } from './ai.js';
import { toolsForTask } from './tools.js';
import { buildArtifactE2EPlan } from './artifact-e2e.js';
import { riskLevel, requiresApproval, requestApproval } from './governance.js';

const ORDER={research:10,'product-planning':20,backend:30,database:40,frontend:50,security:60,testing:70,'artifact-e2e':80};
const SPECS=[['research','Research and validate requirements',['research','analysis'],'internal.plan'],['product-planning','Define product and architecture plan',['product-planning','planning'],'internal.plan'],['backend','Implement backend code and API',['backend','api'],'internal.code'],['database','Implement database and persistence schema',['database','schema','sql'],'internal.code'],['frontend','Implement frontend code and user experience',['frontend','ui'],'internal.code'],['security','Perform security review',['security','audit'],'internal.code'],['testing','Create testing and verification plan',['testing','verification'],'internal.plan']];
const complete=t=>(t?.dependsOn??[]).every(dep=>store.get('tasks',dep)?.state==='completed');
function choose(spec,tools=[]){seedAgents();if(spec.key==='product-planning'||spec.key==='planning'){const p=store.list('agents').find(a=>a.name==='Planning Agent');return p?updateAgent(p.id,{state:'available',currentTaskId:null,heartbeatAt:now()}):registerAgent({name:'Planning Agent',role:'Planner',department:'Planning',capabilities:['product-planning','planning'],tools:['planning.execute']})}return selectAgents(spec.requiredCapabilities,null,{requiredTools:tools,requireAllTools:true})[0]??selectAgents(spec.requiredCapabilities,null,{requireAllTools:false})[0]??null}
function specs(plan,objective){if(plan?.capabilities?.includes('artifact-e2e'))return(plan.artifactSteps??[]).map((s,i)=>({key:'artifact-e2e',title:s.title??`Task ${i+1}`,description:`Create and verify ${s.artifact.path} with exact content.`,requiredCapabilities:['artifact-e2e','testing','verification'],maxAttempts:1,executor:'internal.artifact',sequence:i+1,artifactSpec:s,acceptance:[{field:'type',equals:'artifact'},{field:'artifactVerification.passed',equals:true}]}));const caps=plan?.capabilities??[],req=plan?.requirements??[],list=SPECS.filter(s=>caps.includes(s[0])||s[2].some(c=>caps.includes(c)));return(list.length?list:[['planning','Analyze requirements and produce execution plan',['planning'],'internal.plan']]).map((s,i)=>({key:s[0],title:req[i]?`${s[1]}: ${req[i]}`:s[1],description:objective,requiredCapabilities:s[2],maxAttempts:3,executor:s[3],sequence:ORDER[s[0]]??100+i}));}
export async function prepareCommand(command,env={}){seedAgents();const text=String(command??'').trim();if(!text)throw new Error('Founder command is required');const artifactPlan=buildArtifactE2EPlan(text);let plan=artifactPlan;try{if(!plan&&env?.AI?.run)plan=await interpretWithAI(env,text)}catch{}plan=plan??freePlanFromCommand(text);const objective=plan.objective??text;const risk=riskLevel({codeWrite:/\b(code|coding|build|develop|program|implement)\b/i.test(text)});const project=createProject({name:`Project: ${objective.slice(0,60)}`,objective,founderCommand:text,requirements:plan.requirements??[]});const made=[];for(const s of specs(plan,objective)){const tools=s.executor==='internal.artifact'?[]:toolsForTask({requiredCapabilities:s.requiredCapabilities},{scope:'internal',maxRisk:'read'});const a=choose(s,tools),prev=made.at(-1);const task=addTaskToProject(project.id,{title:s.title,description:s.description,requiredCapabilities:s.requiredCapabilities,risk:s.executor==='internal.artifact'?'low':risk,acceptance:s.acceptance??[{field:'type',equals:s.executor==='internal.code'?'code':'plan'}],assignedAgentId:a?.id??null,toolNames:tools,maxAttempts:s.maxAttempts,executor:s.executor,sequence:s.sequence,dependsOn:prev?[prev.id]:[],artifactSpec:s.artifactSpec??null});if(task)made.push({task,selectedAgent:a});}
remember({type:'project_requirement',content:objective,scope:'project',scopeId:project.id,importance:'high',source:'founder-command'});const approval=requiresApproval(risk)&&requestApproval({action:`Execute founder command: ${text}`,risk,projectId:project.id});return{intent:{id:id('intent'),command:text,objective,capabilities:['requirements']},aiPlan:plan,project,tasks:made,status:approval?'awaiting_approval':'planned',approval};}
