import { id, now } from './core.js';
import { store } from './store.js';
import { executeTool } from './tools.js';
import { code } from './ai.js';
import { registerArtifact } from './artifacts.js';
import { startTask, markVerifying, completeTask, failTask } from './tasks.js';
import { verifyResult, retryDecision } from './verification.js';
import { executeWithAdapter } from './execution-adapter.js';

const handlers = new Map();
const permissions = new Map();
export function registerExecutor(name, handler, meta = {}) { if (!name || typeof handler !== 'function') throw new Error('Executor name and handler are required'); handlers.set(name, { handler, ...meta }); }
export function listExecutors() { return [...handlers.entries()].map(([name, x]) => ({ name, description: x.description ?? '', risk: x.risk ?? 'normal', capabilities: x.capabilities ?? [] })); }
export function grantExecutor(name, scope = 'internal') { permissions.set(name, scope); return { name, scope }; }
function requiredToolNames(task){return [...new Set((task?.toolNames??task?.requiredTools??[]).map(String).filter(Boolean))];}
async function authorizeRequiredTools(task, context, callTool){const required=requiredToolNames(task);const results=[];for(const name of required){const tool=store.list('tools').find(t=>t.name===name&&t.enabled!==false);if(!tool)throw new Error(`Required tool is not registered: ${name}`);const toolContext={type:'authorization-check',taskId:task.id};const authorization=await callTool(name,toolContext);results.push({name,authorization});}return results;}
export async function executeTask(task, context = {}) { const executorName = task.executor ?? 'internal.plan'; const executor = handlers.get(executorName); const existing = task.id ? store.list('runs').filter(r => r.taskId === task.id && r.state === 'running').sort((a,b) => String(b.startedAt).localeCompare(String(a.startedAt)))[0] : null; if (existing && !context.forceRestart) { store.addEvent('execution.recovered', { runId: existing.id, taskId: task.id, executor: executorName }); return existing; } const run = { id:id('run'), taskId:task.id, executor:executorName, state:'running', startedAt:now(), attempt:context.attempt ?? 1, agentId:task.agentId ?? task.assignedAgentId ?? context.agentId ?? null, recoverable:true }; store.put('runs', run); store.addEvent('execution.started', run); try { if (!executor) throw new Error(`No executor registered: ${executorName}`); const scope = permissions.get(executorName) ?? executor.scope ?? 'internal'; if (scope === 'external' && !context.allowExternal) throw new Error('External execution permission is not granted'); if ((executor.risk === 'critical' || task.risk === 'critical') && !context.approved) throw new Error('Critical execution requires explicit approval'); const callTool=(name,input={})=>executeTool(name,input,{...context,agentId:run.agentId,projectId:task.projectId,approved:context.approved,approvalId:context.approvalId}); const requiredTools=await authorizeRequiredTools(task,context,callTool); const result = await executor.handler({ task, ...context, agentId:run.agentId, callTool, requiredTools }); const completed = { ...run, state:'completed', result, requiredTools, completedAt:now(), recoverable:false }; store.put('runs',completed); store.addEvent('execution.completed',completed); return completed; } catch(error) { const failed={...run,state:'failed',error:error.message,completedAt:now(),recoverable:false}; store.put('runs',failed); store.addEvent('execution.failed',failed); return failed; } }
export async function executeTaskLifecycle(task, context = {}) { if (!task?.id) return { status:'failed', error:'Task is required' }; let currentTask=store.get('tasks',task.id)??task; if (currentTask.agentId==null&&currentTask.assignedAgentId!=null) currentTask=store.put('tasks',{...currentTask,agentId:currentTask.assignedAgentId,id:currentTask.id}); if (currentTask.state==='queued'||currentTask.state==='assigned'||currentTask.state==='blocked') { if(currentTask.state==='blocked'&&!context.dependenciesComplete)return{status:'blocked',task:currentTask,reason:currentTask.blockedReason??'Dependencies incomplete'}; currentTask=startTask(currentTask.id)??currentTask; } let attempt=Math.max(1,Number(currentTask.attempts??1)); let execution=await executeTask(currentTask,{...context,attempt,agentId:currentTask.agentId??context.agentId}); let verification=verifyResult(currentTask,execution); currentTask=markVerifying(currentTask.id,execution.result??{error:execution.error})??currentTask; while(!verification.passed){const decision=retryDecision(currentTask,verification,attempt);if(decision.action!=='retry'){const failed=failTask(currentTask.id,execution.error??decision.reason)??currentTask;store.addEvent('task.escalated',{taskId:failed.id,executionId:execution.id,verificationId:verification.id,reason:decision.reason??'verification_failed'});return{status:'escalated',task:failed,execution,verification,decision};}attempt=decision.attempt;currentTask=startTask(currentTask.id)??currentTask;execution=await executeTask(currentTask,{...context,retry:true,attempt,forceRestart:true,agentId:currentTask.agentId??context.agentId});verification=verifyResult(currentTask,execution);currentTask=markVerifying(currentTask.id,execution.result??{error:execution.error})??currentTask;} const completed=completeTask(currentTask.id,execution.result??{})??currentTask;store.addEvent('task.execution_lifecycle_completed',{taskId:completed.id,executionId:execution.id,verificationId:verification.id,attempts:completed.attempts});return{status:'completed',task:completed,execution,verification}; }
export function recoverRunningExecutions(){return store.list('runs').filter(run=>run.state==='running').map(run=>{store.addEvent('execution.recovery_candidate',{runId:run.id,taskId:run.taskId,executor:run.executor});return run;});}
async function repairCodeArtifact({ env, task, artifact, runtime, attempt }) { const prompt=['You are the MAULI Coding Repair Agent.','A generated code artifact failed execution. Analyze the runtime failure and return corrected JSON only.', 'Schema: {"summary":string,"files":[{"path":string,"content":string}],"tests":string[],"notes":string[]}.','Preserve working files and make the smallest safe correction.',`Task: ${task.title??''}`,`Acceptance criteria: ${JSON.stringify(task.acceptance??[])}`,`Previous artifact: ${JSON.stringify(artifact.content)}`,`Runtime failure: ${JSON.stringify(runtime)}`,`Repair attempt: ${attempt}`].join('\n'); const raw=await code(env,[{role:'system',content:'Repair code using the reported execution failure. Never claim tests passed unless the runner result proves it.'},{role:'user',content:prompt}]); let parsed;try{parsed=typeof raw==='string'?JSON.parse(raw):raw;}catch{throw new Error('Coding repair response was not valid JSON');} const files=Array.isArray(parsed?.files)?parsed.files.filter(f=>f&&typeof f.path==='string'&&typeof f.content==='string'):[]; if(!files.length)throw new Error('Coding repair returned no files'); return registerArtifact({projectId:task.projectId,taskId:task.id,agentId:task.agentId??task.assignedAgentId,type:'code-workspace',content:{summary:String(parsed.summary??'Repaired code artifact'),files,tests:Array.isArray(parsed.tests)?parsed.tests:[],notes:Array.isArray(parsed.notes)?parsed.notes:[]},metadata:{generatedBy:'internal.code-repair',repairAttempt:attempt,previousArtifactId:artifact.id}}); }
registerExecutor('internal.plan',async({task,callTool})=>({type:'plan',taskId:task.id,output:'Execution plan generated.',diagnostics:await callTool('health.check')}),{description:'Safe internal planning executor',risk:'low',scope:'internal'});grantExecutor('internal.plan','internal');
registerExecutor('internal.code',async({task,env,agentId})=>{ if(!env)throw new Error('AI runtime environment is required for coding'); const prompt=['You are the MAULI Coding Agent.','Produce implementation artifacts for the task.','Return JSON only with this schema: {"summary":string,"files":[{"path":string,"content":string}],"tests":[string],"notes":[string]}.','Do not claim that files were written or tests were executed.',`Task: ${task.title??'Coding task'}`,`Objective: ${task.description??''}`,`Required capabilities: ${(task.requiredCapabilities??[]).join(', ')}`,`Acceptance criteria: ${JSON.stringify(task.acceptance??[])}`].join('\n'); const raw=await code(env,[{role:'system',content:'Generate safe, minimal, production-oriented code artifacts.'},{role:'user',content:prompt}]); let parsed;try{parsed=typeof raw==='string'?JSON.parse(raw):raw;}catch{parsed={summary:'Code artifact generated as raw model output.',files:[],tests:[],notes:[String(raw)]};} const files=Array.isArray(parsed?.files)?parsed.files.filter(file=>file&&typeof file.path==='string'&&typeof file.content==='string'):[]; const artifact=registerArtifact({projectId:task.projectId,taskId:task.id,agentId,type:'code-workspace',content:{summary:String(parsed?.summary??'Code artifact'),files,tests:Array.isArray(parsed?.tests)?parsed.tests:[],notes:Array.isArray(parsed?.notes)?parsed.notes:[]},metadata:{generatedBy:'internal.code'}}); store.addEvent('artifact.generated',{artifactId:artifact.id,taskId:task.id,fileCount:files.length}); return{type:'code',artifactId:artifact.id,summary:artifact.content.summary,files:artifact.content.files,tests:artifact.content.tests,notes:artifact.content.notes}; },{description:'Generates code workspace artifacts using the MAULI Intelligence Bus',risk:'low',scope:'internal',capabilities:['coding','software-development']});grantExecutor('internal.code','internal');
registerExecutor('internal.verify-code',async({task,adapter='local-node'})=>{ const artifacts=task.id?store.list('artifacts').filter(a=>a.taskId===task.id&&a.type==='code-workspace'):[]; const artifact=artifacts.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]; if(!artifact)return{type:'code-verification',passed:false,checks:[{name:'artifact_exists',passed:false}],message:'No code artifact found'}; const files=Array.isArray(artifact.content?.files)?artifact.content.files:[]; const tests=Array.isArray(artifact.content?.tests)?artifact.content.tests:[]; const checks=[{name:'artifact_exists',passed:true},{name:'files_present',passed:files.length>0},{name:'valid_file_paths',passed:files.every(f=>!f.path.startsWith('/')&&!f.path.includes('..'))},{name:'non_empty_files',passed:files.every(f=>f.content.trim().length>0)},{name:'test_plan_present',passed:tests.length>0}]; const staticPassed=checks.every(c=>c.passed); let runtime=null; if(staticPassed&&adapter!=='none'){try{runtime=await executeWithAdapter(adapter,{artifact,task,command:task.testCommand?.command??'node',args:task.testCommand?.args??[],timeoutMs:task.testCommand?.timeoutMs??10000});}catch(error){runtime={adapter,status:'error',executed:false,error:error.message};}} const passed=staticPassed&&Boolean(runtime?.executed)&&runtime.status==='accepted'; return{type:'code-verification',artifactId:artifact.id,passed,checks,runtime,mode:runtime?.executed?'local-runtime':'static-artifact-verification',message:passed?'Artifact passed L1 verification.':'Artifact failed L1 verification.'};},{description:'Runs and verifies generated code using the zero-cost local execution adapter',risk:'low',scope:'internal',capabilities:['testing','verification']});grantExecutor('internal.verify-code','internal');
