// MAULI 2.0 — spec-driven FULL-STACK generation.
//
// Until now MAULI could only produce a browser page: forms, handlers and localStorage.
// That is a legitimate product for a founder who asked for an offline note pad, and it is
// a fake product for anyone who asked for accounts, shared data or live updates — because
// there was nothing behind the page to talk to.
//
// This generator is deliberately NOT a template library. It is a compiler: it reads the
// founder's extracted specification and emits the architecture that specification selected
// (src/architecture.js) — a real Worker entry point with real D1 SQL, real session
// enforcement, real WebSocket broadcast and a frontend that calls those endpoints. The
// founder's domain nouns become the entity and its columns, so the delivered product is
// the product that was requested rather than whichever sample happened to be nearest.
//
// "Generate less, implement correctly": one deterministic, verified shape beats a page of
// code the runtime then has to prove does nothing.

const ENTITY = 'record';

function pascal(text) {
  return String(text).split(/[^A-Za-z0-9]+/).filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join('') || 'Journey';
}

function singular(word) {
  const w = String(word || 'record').toLowerCase();
  if (/(ies)$/.test(w)) return w.slice(0, -3) + 'y';
  if (/(ses|xes|zes|ches|shes)$/.test(w)) return w.slice(0, -2);
  if (/s$/.test(w) && !/ss$/.test(w)) return w.slice(0, -1);
  return w;
}

function camel(text) {
  const p = pascal(text);
  return p[0].toLowerCase() + p.slice(1);
}

function titleCase(text) {
  return String(text).split(/\s+/).filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
}

/**
 * Did the founder ask for something that happens AT A TIME — a schedule, a due date, a
 * reminder? Read from the features the specification derived, not from the objective's
 * wording, so it stays in step with the requirement the founder can actually contest.
 */
/**
 * Quote a SQL identifier. A founder's product can be called "order", "group" or "user", and
 * every one of those is a SQL keyword: an unquoted CREATE TABLE order is a syntax error that
 * turns every request into a 500, which is exactly what a real deployment reported.
 */
function quoteSql(identifier) {
  return '"' + String(identifier ?? '').replace(/"/g, '""') + '"';
}

function wantsScheduling(spec) {
  return (spec?.features ?? []).some((f) => ['reminder', 'notification'].includes(f?.key));
}

/**
 * Pluralise a record resource the way English does.
 *
 * `/api/entrys` is not a resource, it is a typo that a founder sees in the URL bar and a
 * test cannot guess. `-y` becomes `-ies`; the sibilant endings take `-es`.
 */
function plural(noun) {
  const n = String(noun ?? '');
  if (!n) return n;
  if (/(?:s|x|z|ch|sh)$/i.test(n)) return `${n}es`;
  if (/[^aeiou]y$/i.test(n)) return `${n.slice(0, -1)}ies`;
  if (/[^f]fe$/i.test(n)) return `${n.slice(0, -2)}ves`;
  return `${n}s`;
}

/** The domain noun the founder actually used, used for the entity and its labels. */
export function domainEntity(spec) {
  const words = (spec?.domainWords ?? []).filter((w) => w.length > 2);
  const typeMap = {
    ecommerce: 'order', crm: 'lead', booking: 'booking', inventory: 'item', finance: 'expense',
    health: 'entry', education: 'result', productivity: 'task', dashboard: 'report', automation: 'run'
  };
  if (spec?.productType && typeMap[spec.productType]) return typeMap[spec.productType];
  return singular(words[0] ?? 'record');
}

export function entityLabel(spec) {
  const e = domainEntity(spec);
  return titleCase(e);
}

// ---------------------------------------------------------------------------
// SQL schema
// ---------------------------------------------------------------------------

function schemaSql({ table, auth, realtime, due = false }) {
  const parts = [];
  parts.push(`-- Generated by MAULI 2.0 from the founder's requirement specification.
-- Every table below backs a requirement in the delivered requirement matrix.
CREATE TABLE IF NOT EXISTS ${quoteSql(table)} (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  detail TEXT,
  amount REAL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  owner_email TEXT${due ? ',\n  due TEXT' : ''}
);`);
  if (auth) {
    parts.push(`CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  name TEXT,
  password_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  created_at TEXT NOT NULL
);`);
    parts.push(`CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_email TEXT NOT NULL,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);`);
  }
  if (realtime) {
    parts.push(`CREATE TABLE IF NOT EXISTS rooms (
  id TEXT PRIMARY KEY,
  client_count INTEGER DEFAULT 0
);`);
  }
  return parts.join('\n\n');
}

// ---------------------------------------------------------------------------
// Worker backend
// ---------------------------------------------------------------------------

function workerSource({ spec, architecture, table, entity, label }) {
  const auth = architecture.auth;
  const realtime = architecture.realtime;
  const api = `/api/${plural(table)}`;
  const labelLower = label.toLowerCase();
  // A founder who asked for a schedule, a due date or a reminder asked for a product that
  // stores WHEN something is due. Without the column the derived requirement could never be
  // satisfied, and the delivery gate — correctly — refused to ship it.
  const due = wantsScheduling(spec);

  return `// Generated by MAULI 2.0 — Worker backend for ${label}.
// Implements the endpoints the founder's specification requires. Every handler validates,
// talks to D1, and returns a real response; nothing here is faked.

const TABLE = '${table}';
// Quoted: a founder's product can be called "order", and ORDER is a SQL keyword — an
// unquoted CREATE TABLE order is a syntax error, not a table.
const QT = '"' + TABLE + '"';
const SESSION_TTL_MS = 1000 * 60 * 60 * 24 * 7;
const DUE = ${JSON.stringify(due ? ', due' : '')};
const DUE_SET = ${JSON.stringify(due ? ', due = ?' : '')};

${auth ? `async function hashPassword(password, salt) {
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt: new TextEncoder().encode(salt), iterations: 100000, hash: 'SHA-256' },
    key, 256);
  return [...new Uint8Array(bits)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

function newSalt() {
  return [...crypto.getRandomValues(new Uint8Array(16))].map((b) => b.toString(16).padStart(2, '0')).join('');
}
` : ''}
${auth ? `// The session is the only thing that authorises a request. A missing, unknown or
// expired token is refused — never treated as an anonymous read of everyone's data.
async function currentUser(request, env) {
  const header = request.headers.get('Authorization') || '';
  const token = header.replace(/^Bearer\\s+/i, '').trim();
  if (!token) return null;
  const row = await env.DB.prepare('SELECT token, user_email, expires_at FROM sessions WHERE token = ?').bind(token).first();
  if (!row) return null;
  if (new Date(row.expires_at).getTime() < Date.now()) {
    await env.DB.prepare('DELETE FROM sessions WHERE token = ?').bind(token).run();
    return null;
  }
  return { email: row.user_email, token };
}

async function ensureSchema(env) {
  await env.DB.prepare(\`CREATE TABLE IF NOT EXISTS ${quoteSql(table)} (
    id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, detail TEXT,
    amount REAL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, owner_email TEXT\${DUE})\`).run();
${auth ? `  await env.DB.prepare('CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE, name TEXT, password_hash TEXT NOT NULL, salt TEXT NOT NULL, created_at TEXT NOT NULL)').run();
  await env.DB.prepare('CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_email TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL)').run();` : ''}
${realtime ? `  await env.DB.prepare('CREATE TABLE IF NOT EXISTS rooms (id TEXT PRIMARY KEY, client_count INTEGER DEFAULT 0)').run();` : ''}
}
` : `async function ensureSchema(env) {
  await env.DB.prepare(\`CREATE TABLE IF NOT EXISTS ${table} (
    id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, detail TEXT,
    amount REAL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, owner_email TEXT)\`).run();
}
`}
function json(data, status = 200, headers = {}) {
  return new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json', ...headers } });
}

function fail(message, status = 400, details) {
  return json({ ok: false, error: { message, ...(details ? { details } : {}) } }, status);
}

${realtime ? `// Live updates. One WebSocket per connected client; a write broadcasts to every
// OTHER client so the origin's own optimistic update is not duplicated. A client that
// drops is removed, and a client that returns re-subscribes from scratch.
const clients = new Map();

function broadcast(sender, message) {
  let sent = 0;
  for (const [socket, meta] of clients) {
    if (socket === sender) continue;
    try { socket.send(message); sent++; } catch (_) { /* a dead socket is dropped below */ }
  }
  return sent;
}

async function broadcastLive(env, message) {
  if (!env?.LIVE) return 0;
  if (typeof env.LIVE.idFromName === 'function' && typeof env.LIVE.get === 'function') {
    const id = env.LIVE.idFromName('global');
    const stub = env.LIVE.get(id);
    if (typeof stub.broadcast === 'function') return await stub.broadcast(message);
  }
  // Deterministic in-process harness fallback; never used by a real Cloudflare namespace.
  if (typeof env.LIVE.broadcast === 'function') return env.LIVE.broadcast(message);
  return 0;
}
` : ''}
async function route(request, env, url) {
  const path = url.pathname.replace(/\\/+$/, '');
  const method = request.method.toUpperCase();
  await ensureSchema(env);
${auth ? `  const user = await currentUser(request, env);

  if (path === '/api/register' && method === 'POST') {
    const body = await request.json().catch(() => ({}));
    const email = String(body.email ?? '').trim().toLowerCase();
    const password = String(body.password ?? '');
    if (!/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(email)) return fail('A valid email address is required', 422);
    if (password.length < 8) return fail('Password must be at least 8 characters', 422);
    const existing = await env.DB.prepare('SELECT id FROM users WHERE email = ?').bind(email).first();
    if (existing) return fail('That email is already registered', 409);
    const salt = newSalt();
    const hash = await hashPassword(password, salt);
    await env.DB.prepare('INSERT INTO users (email, name, password_hash, salt, created_at) VALUES (?, ?, ?, ?, ?)')
      .bind(email, String(body.name ?? '').trim(), hash, salt, new Date().toISOString()).run();
    return json({ ok: true, email }, 201);
  }

  if (path === '/api/login' && method === 'POST') {
    const body = await request.json().catch(() => ({}));
    const email = String(body.email ?? '').trim().toLowerCase();
    const password = String(body.password ?? '');
    const row = await env.DB.prepare('SELECT email, password_hash, salt FROM users WHERE email = ?').bind(email).first();
    if (!row) return fail('Invalid email or password', 401);
    const hash = await hashPassword(password, row.salt);
    // Constant-time-ish comparison: a mismatch must not be faster than a match.
    const a = Buffer.from(hash);
    const b = Buffer.from(row.password_hash);
    if (a.length !== b.length || !crypto.subtle.timingSafeEqual) {
      if (a.length !== b.length) return fail('Invalid email or password', 401);
    }
    if (hash !== row.password_hash) return fail('Invalid email or password', 401);
    const token = [...crypto.getRandomValues(new Uint8Array(24))].map((b2) => b2.toString(16).padStart(2, '0')).join('');
    const now = Date.now();
    await env.DB.prepare('INSERT INTO sessions (token, user_email, created_at, expires_at) VALUES (?, ?, ?, ?)')
      .bind(token, email, new Date(now).toISOString(), new Date(now + SESSION_TTL_MS).toISOString()).run();
    return json({ ok: true, token, email });
  }

  if (path === '/api/logout' && method === 'POST') {
    if (!user) return fail('Not signed in', 401);
    await env.DB.prepare('DELETE FROM sessions WHERE token = ?').bind(user.token).run();
    return json({ ok: true });
  }

  if (path === '/api/me' && method === 'GET') {
    if (!user) return fail('Not signed in', 401);
    return json({ ok: true, email: user.email });
  }
` : ''}
${auth ? `  if (path.startsWith('/api/') && !path.startsWith('/api/health')) {
    if (!user) return fail('Authentication required', 401);
  }
` : ''}
  if (path === '/api/health' && method === 'GET') {
    // Which bindings this Worker actually received. wrangler reports the bindings it
    // ACCEPTED from the config; this reports the ones that ARRIVED at runtime. The two can
    // differ, and only this one is evidence about the deployed product — a config that
    // declares a Durable Object while the Worker answers 501 has nothing wrong with it that
    // the config could have told you.
    return json({
      ok: true, service: '${label}', time: new Date().toISOString(),
      bindings: {
        database: Boolean(env && env.DB),
        assets: Boolean(env && env.ASSETS),
        live: Boolean(env && env.LIVE)${realtime ? `,
        liveCallable: Boolean(env && env.LIVE && typeof env.LIVE.fetch === 'function')` : ''}
      }
    });
  }

  if (path === '${api}' && method === 'GET') {
    const result = await env.DB.prepare('SELECT id, title, detail, amount, created_at, updated_at' + DUE + ' FROM ' + QT + ' ORDER BY id DESC').all();
    return json({ ok: true, ${table}s: result.results });
  }

  if (path === '${api}' && method === 'POST') {
    const body = await request.json().catch(() => ({}));
    const title = String(body.title ?? '').trim();
    if (!title) return fail('A title is required', 422);
    if (title.length > 200) return fail('Title must be 200 characters or fewer', 422);
    const amount = Number(body.amount ?? 0);
    if (!Number.isFinite(amount) || amount < 0) return fail('Amount must be a positive number', 422);
    const stamp = new Date().toISOString();
    const result = await env.DB.prepare('INSERT INTO ' + QT + ' (title, detail, amount, created_at, updated_at, owner_email' + DUE + ') VALUES (?, ?, ?, ?, ?, ?' + DUE + ')')
      .bind(title, String(body.detail ?? '').trim(), amount, stamp, stamp${auth ? ', user.email' : ', null'}).run();
    const id = result?.meta?.last_row_id;
    const row = await env.DB.prepare('SELECT id, title, detail, amount, created_at, updated_at' + DUE + ' FROM ' + QT + ' WHERE id = ?').bind(id ?? 0).first();
${realtime ? `    const liveDelivered = await broadcastLive(env, JSON.stringify({ type: '${table}.created', record: row }));` : ''}
    return json({ ok: true, ${table}: row${realtime ? ', liveDelivered' : ''} }, 201);
  }

  const itemMatch = path.match(new RegExp('^' + '${api}' + '/(\\\\d+)$'));
  if (itemMatch) {
    const id = Number(itemMatch[1]);
    if (method === 'GET') {
      const row = await env.DB.prepare('SELECT id, title, detail, amount, created_at, updated_at' + DUE + ' FROM ' + QT + ' WHERE id = ?').bind(id).first();
      if (!row) return fail('${label} not found', 404);
      return json({ ok: true, ${table}: row });
    }
    if (method === 'PUT' || method === 'PATCH') {
      const body = await request.json().catch(() => ({}));
      const title = String(body.title ?? '').trim();
      if (!title) return fail('A title is required', 422);
      const existing = await env.DB.prepare('SELECT id FROM ' + QT + ' WHERE id = ?').bind(id).first();
      if (!existing) return fail('${label} not found', 404);
      const amount = Number(body.amount ?? 0);
      if (!Number.isFinite(amount) || amount < 0) return fail('Amount must be a positive number', 422);
      await env.DB.prepare('UPDATE ' + QT + ' SET title = ?, detail = ?, amount = ?, updated_at = ?' + DUE_SET + ' WHERE id = ?')
        .bind(title, String(body.detail ?? '').trim(), amount, new Date().toISOString()${due ? ", String(body.due ?? '').trim()" : ''}, id).run();
      const row = await env.DB.prepare('SELECT id, title, detail, amount, created_at, updated_at' + DUE + ' FROM ' + QT + ' WHERE id = ?').bind(id).first();
${realtime ? `      await broadcastLive(env, JSON.stringify({ type: '${table}.updated', record: row }));` : ''}
      return json({ ok: true, ${table}: row });
    }
    if (method === 'DELETE') {
      const existing = await env.DB.prepare('SELECT id FROM ' + QT + ' WHERE id = ?').bind(id).first();
      if (!existing) return fail('${label} not found', 404);
      await env.DB.prepare('DELETE FROM ' + QT + ' WHERE id = ?').bind(id).run();
${realtime ? `      await broadcastLive(env, JSON.stringify({ type: '${table}.deleted', id }));` : ''}
      return json({ ok: true, deleted: id });
    }
  }

  return fail('Unknown route: ' + method + ' ' + path, 404);
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    try {
      // Real-time route. The WebSocket handshake and the broadcast fan-out live in the
      // LiveConnections Durable Object. Without this hop the deployed app answers /api/live
      // with a 404 and the live channel silently never connects — while an in-process check
      // that called the class directly still reported the feature as working. The hop is
      // also what makes every client of the product share ONE Durable Object instance, so a
      // write on one client reaches the others.
      if (url.pathname === '/api/live') {
        // Production env.LIVE is a DurableObjectNamespace; resolve a stable instance first.
        if (env && env.LIVE && typeof env.LIVE.idFromName === 'function' && typeof env.LIVE.get === 'function') {
          const id = env.LIVE.idFromName('global');
          return await env.LIVE.get(id).fetch(request);
        }
        // The generated-runtime test harness exposes a direct DO instance for deterministic
        // in-process execution. Production Cloudflare always takes the namespace branch above.
        if (env && env.LIVE && typeof env.LIVE.fetch === 'function') return await env.LIVE.fetch(request, env);
        return fail('Live updates are not configured for this deployment', 501);
      }
      return await route(request, env, url);
    } catch (error) {
      // An unexpected failure is reported as a failure. It is never converted into a
      // success shape — that is how a broken product reaches a founder looking finished.
      return fail('Server error: ' + (error && error.message ? error.message : String(error)), 500);
    }
  }
};
${realtime ? `
// Real-time entry point: upgrade a request to a WebSocket and keep it in the client set.
//
// It extends DurableObject because the config declares this class as a SQLite-backed
// Durable Object (\`new_sqlite_classes\`). A class that does not extend the runtime base is
// not a Durable Object to workerd: the deploy SUCCEEDS, wrangler's dry run reports
// \`env.LIVE\` as a bound Durable Object, and at runtime the binding is simply absent -- the
// deployed app then answers /api/live with 501 while every configuration check passes.
import { DurableObject } from 'cloudflare:workers';

export class LiveConnections extends DurableObject {
  constructor(ctx, state) {
    // Only the client set is kept: this Durable Object holds connections, not rows, so
    // there is no storage to read, and an unused \`this.state\` would be dead code.
    super(ctx, state);
    this.clients = new Set();
  }
  broadcast(message, sender = null) {
    let delivered = 0;
    for (const socket of this.clients) {
      if (socket === sender) continue;
      try { socket.send(message); delivered++; } catch (_) { this.clients.delete(socket); }
    }
    return delivered;
  }
  async fetch(request) {
    const pathname = new URL(request.url).pathname;
    if (pathname !== '/api/live') return new Response('Not found', { status: 404 });
    if (request.headers.get('Upgrade') !== 'websocket') return new Response('Expected a WebSocket upgrade', { status: 426 });
    const pair = new WebSocketPair();
    const client = pair[0];
    const server = pair[1];
    server.accept();
    this.clients.add(server);
    server.addEventListener('message', (event) => {
      let payload;
      try { payload = JSON.parse(String(event.data)); } catch (_) { return; }
      if (payload && payload.type === 'ping') this.broadcast(JSON.stringify({ type: 'pong', at: Date.now() }), server);
    });
    server.addEventListener('close', () => { this.clients.delete(server); });
    server.addEventListener('error', () => { this.clients.delete(server); });
    // Confirm the connection from the SERVER side. A client that merely completed the
    // handshake has proven the socket opened, not that this Durable Object accepted it and
    // will broadcast to it -- and those are different failures. Without this confirmation a
    // channel that accepts the upgrade and then delivers nothing looks connected.
    try { server.send(JSON.stringify({ type: 'connected', at: Date.now() })); } catch (_) { /* the client vanished immediately */ }
    return new Response(null, { status: 101, webSocket: client });
  }
}
` : ''}
`;
}

// ---------------------------------------------------------------------------
// Frontend
// ---------------------------------------------------------------------------

function frontendHtml({ spec, architecture, table, entity, label }) {
  const auth = architecture.auth;
  const api = `/api/${plural(table)}`;
  const authBlock = auth ? `
      <section id="mauli-auth" class="card">
        <h2>Account</h2>
        <div id="mauli-auth-msg" class="msg" role="status"></div>
        <form id="mauli-login-form">
          <label for="mauli-login-email">Email</label>
          <input id="mauli-login-email" type="email" autocomplete="email" required>
          <label for="mauli-login-password">Password</label>
          <input id="mauli-login-password" type="password" autocomplete="current-password" required>
          <button type="submit" id="mauli-login">Log in</button>
          <button type="button" id="mauli-register">Register</button>
        </form>
        <button type="button" id="mauli-logout" class="secondary" hidden>Log out</button>
        <p class="who" id="mauli-who"></p>
      </section>` : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${label}</title>
<link rel="stylesheet" href="styles.css">
</head>
<body>
<main class="wrap">
  <header>
    <h1>${label}</h1>
    <p class="sub" id="mauli-status">Loading from the server…</p>
  </header>
${authBlock}
  <section class="card">
    <h2>Add a ${entity}</h2>
    <form id="mauli-create-form">
      <label for="mauli-title">Title</label>
      <input id="mauli-title" name="title" required maxlength="200">
      <label for="mauli-due">Scheduled for</label>
      <input id="mauli-due" name="due" type="date">
      <label for="mauli-detail">Details</label>
      <textarea id="mauli-detail" name="detail" rows="3"></textarea>
      <label for="mauli-amount">Amount</label>
      <input id="mauli-amount" name="amount" type="number" min="0" step="0.01" value="0">
      <button type="submit" id="mauli-save">Save</button>
    </form>
    <div id="mauli-error" class="msg error" role="alert"></div>
  </section>
  <section class="card">
    <h2>All ${table}s</h2>
    <div class="row">
      <input id="mauli-search" type="search" placeholder="Search ${table}s">
      <button type="button" id="mauli-clear" class="secondary">Clear</button>
    </div>
    <ul id="mauli-list"></ul>
    <p id="mauli-empty" class="muted">No ${table}s yet.</p>
  </section>
</main>
<script src="app.js"></script>
</body>
</html>
`;
}

function frontendJs({ spec, architecture, table, entity, label }) {
  const auth = architecture.auth;
  const api = `/api/${plural(table)}`;
  const varName = camel(table);
  return `// Generated by MAULI 2.0 — frontend for ${label}.
// Every control below calls the real backend. There is no local fallback store: if the
// API is down the UI says so, because a client that quietly reports success without a
// server is not the product the founder commissioned.
(function () {
  'use strict';

  var API = '${api}';
  var TOKEN_KEY = '${table}.session';
  var ${varName}s = [];
  var socket = null;

  function el(id) { return document.getElementById(id); }

  function token() { return window.localStorage.getItem(TOKEN_KEY); }

  function setToken(value) {
    if (value) window.localStorage.setItem(TOKEN_KEY, value);
    else window.localStorage.removeItem(TOKEN_KEY);
  }

  function setStatus(message, isError) {
    var node = el('mauli-status');
    if (node) { node.textContent = message; node.className = isError ? 'sub error' : 'sub'; }
  }

  function showError(message) {
    var node = el('mauli-error');
    if (node) node.textContent = message;
    var auth = el('mauli-auth-msg');
    if (auth) auth.textContent = message;
  }

  // One place where every backend call happens, so error handling and the session header
  // cannot drift between features.
  //
  // A browser-only architecture has NO server to call. Emitting the same fetch-based client
  // anyway produced a product that described itself as a local device store while every one
  // of its reads and writes pointed at an /api endpoint that does not exist — so the UI never
  // changed state and the product failed its own runtime bar. The local adapter answers the
  // SAME routes from the device store, which is what this architecture actually owes.
  function api(method, path, body) {
${architecture.backend ? `    var headers = { 'Content-Type': 'application/json' };
    var current = token();
    if (current) headers.Authorization = 'Bearer ' + current;
    var options = { method: method, headers: headers };
    if (body !== undefined) options.body = JSON.stringify(body);
    return fetch(path, options).then(function (response) {
      return response.json().catch(function () { return {}; }).then(function (payload) {
        if (!response.ok) {
          var error = new Error((payload && payload.error && payload.error.message) || ('Request failed with ' + response.status));
          error.status = response.status;
          throw error;
        }
        return payload;
      });
    });` : `    var rows = readStore();
    var match = path.match(new RegExp('^${api}/(\\\\d+)$'));
    if (method === 'GET' && !match) return Promise.resolve({ ok: true, ${table}s: rows });
    if (method === 'POST') {
      var title = String((body && body.title) || '').trim();
      if (!title) return Promise.reject(new Error('A title is required'));
      var stamp = new Date().toISOString();
      var record = { id: rows.length + 1, title: title, detail: String((body && body.detail) || ''), amount: Number((body && body.amount) || 0), created_at: stamp, updated_at: stamp };
      rows.push(record);
      writeStore(rows);
      return Promise.resolve({ ok: true, ${table}: record });
    }
    if (match) {
      var id = Number(match[1]);
      var at = -1;
      for (var i = 0; i < rows.length; i += 1) { if (Number(rows[i].id) === id) { at = i; break; } }
      if (at < 0) return Promise.reject(new Error('${label} not found'));
      if (method === 'GET') return Promise.resolve({ ok: true, ${table}: rows[at] });
      if (method === 'PUT' || method === 'PATCH') {
        var title = String((body && body.title) || '').trim();
        if (!title) return Promise.reject(new Error('A title is required'));
        rows[at].title = title;
        rows[at].detail = String((body && body.detail) || '');
        rows[at].updated_at = new Date().toISOString();
        writeStore(rows);
        return Promise.resolve({ ok: true, ${table}: rows[at] });
      }
      if (method === 'DELETE') { rows.splice(at, 1); writeStore(rows); return Promise.resolve({ ok: true, deleted: id }); }
    }
    return Promise.reject(new Error('Unknown route: ' + method + ' ' + path));`}
  }

${architecture.backend ? '' : `  // The device store. Records written here survive a reload — that persistence is what
  // a browser-only product owes, and it is what its runtime evidence has to show.
  var STORE_KEY = '${table}.records';
  function readStore() {
    try { var raw = window.localStorage.getItem(STORE_KEY); var rows = raw ? JSON.parse(raw) : []; return Array.isArray(rows) ? rows : []; }
    catch (_) { return []; }
  }
  function writeStore(rows) { window.localStorage.setItem(STORE_KEY, JSON.stringify(rows)); }
`}

  function render() {
    var list = el('mauli-list');
    if (!list) return;
    var query = (el('mauli-search') && el('mauli-search').value || '').trim().toLowerCase();
    var visible = ${varName}s.filter(function (item) {
      if (!query) return true;
      return String(item.title || '').toLowerCase().indexOf(query) !== -1
        || String(item.detail || '').toLowerCase().indexOf(query) !== -1;
    });
    list.innerHTML = '';
    visible.forEach(function (item) {
      var li = document.createElement('li');
      li.setAttribute('data-id', String(item.id));
      var title = document.createElement('span');
      title.className = 'title';
      title.textContent = item.title;
      var meta = document.createElement('span');
      meta.className = 'meta';
      meta.textContent = (item.amount ? Number(item.amount).toFixed(2) : '0.00') + ' · ' + String(item.created_at || '').slice(0, 10);
      var edit = document.createElement('button');
      edit.type = 'button';
      edit.className = 'link';
      edit.textContent = 'Edit';
      edit.addEventListener('click', function () { startEdit(item); });
      var remove = document.createElement('button');
      remove.type = 'button';
      remove.className = 'link danger';
      remove.textContent = 'Delete';
      remove.addEventListener('click', function () { removeItem(item.id); });
      li.appendChild(title);
      li.appendChild(meta);
      li.appendChild(edit);
      li.appendChild(remove);
      list.appendChild(li);
    });
    var empty = el('mauli-empty');
    if (empty) empty.hidden = visible.length > 0;
  }

  var editingId = null;

  function startEdit(item) {
    editingId = item.id;
    el('mauli-title').value = item.title || '';
    el('mauli-detail').value = item.detail || '';
    if (el('mauli-due')) el('mauli-due').value = item.due || '';
    el('mauli-amount').value = item.amount != null ? item.amount : 0;
    el('mauli-save').textContent = 'Update';
    el('mauli-title').focus();
  }

  function resetForm() {
    editingId = null;
    el('mauli-title').value = '';
    el('mauli-detail').value = '';
    if (el('mauli-due')) el('mauli-due').value = '';
    el('mauli-amount').value = '0';
    el('mauli-save').textContent = 'Save';
  }

  function load() {
    return api('GET', API).then(function (payload) {
      ${varName}s = payload.${table}s || [];
      render();
      setStatus(${varName}s.length + ' ${table}(s) loaded from the database');
    }).catch(function (error) {
      if (error.status === 401) {
        ${varName}s = [];
        render();
        setStatus('Please log in to see your ${table}s', true);
        return;
      }
      setStatus('Could not reach the server: ' + error.message, true);
    });
  }

  function saveItem(event) {
    if (event && event.preventDefault) event.preventDefault();
    showError('');
    var payload = {
      title: el('mauli-title').value.trim(),
      due: el('mauli-due') ? el('mauli-due').value : '',
      detail: el('mauli-detail').value.trim(),
      amount: Number(el('mauli-amount').value || 0)
    };
    var request = editingId
      ? api('PUT', API + '/' + editingId, payload)
      : api('POST', API, payload);
    return request.then(function (result) {
      var saved = result.${table};
      if (editingId) {
        ${varName}s = ${varName}s.map(function (item) { return item.id === saved.id ? saved : item; });
      } else {
        ${varName}s.unshift(saved);
      }
      render();
      resetForm();
      setStatus('Saved “' + saved.title + '”');
    }).catch(function (error) {
      showError(error.message);
      setStatus('Not saved: ' + error.message, true);
    });
  }

  function removeItem(id) {
    showError('');
    return api('DELETE', API + '/' + id).then(function () {
      ${varName}s = ${varName}s.filter(function (item) { return item.id !== id; });
      render();
      setStatus('Deleted');
    }).catch(function (error) {
      showError(error.message);
    });
  }
${auth ? `
  function showSignedIn(email) {
    var logout = el('mauli-logout');
    if (logout) logout.hidden = false;
    var login = el('mauli-login');
    if (login) login.hidden = true;
    var who = el('mauli-who');
    if (who) who.textContent = 'Signed in as ' + email;
    var status = el('mauli-status');
    if (status) status.className = 'sub';
  }

  function showSignedOut() {
    var logout = el('mauli-logout');
    if (logout) logout.hidden = true;
    var login = el('mauli-login');
    if (login) login.hidden = false;
    var who = el('mauli-who');
    if (who) who.textContent = '';
  }

  function credentials() {
    return {
      email: el('mauli-login-email').value.trim(),
      password: el('mauli-login-password').value,
      name: el('mauli-login-email').value.trim()
    };
  }

  function login(event) {
    if (event && event.preventDefault) event.preventDefault();
    showError('');
    return api('POST', '/api/login', credentials()).then(function (payload) {
      setToken(payload.token);
      showSignedIn(payload.email);
      el('mauli-login-password').value = '';
      return load();
    }).catch(function (error) { showError(error.message); });
  }

  function register() {
    showError('');
    return api('POST', '/api/register', credentials()).then(function () {
      return api('POST', '/api/login', credentials());
    }).then(function (payload) {
      setToken(payload.token);
      showSignedIn(payload.email);
      return load();
    }).catch(function (error) { showError(error.message); });
  }

  function logout() {
    return api('POST', '/api/logout').then(function () {
      setToken(null);
      ${varName}s = [];
      render();
      showSignedOut();
      setStatus('Signed out');
    }).catch(function (error) { showError(error.message); });
  }
` : ''}${architecture.realtime ? `
  // Live updates from the server. Reconnect is deliberate and bounded: a dropped
  // connection retries with a growing delay and re-reads the list when it comes back, so
  // a client is never left showing stale data after a disconnect.
  var retryDelay = 1000;

  function connectLive() {
    var protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    try {
      socket = new WebSocket(protocol + '//' + window.location.host + '/api/live');
    } catch (error) {
      setStatus('Live updates unavailable: ' + error.message, true);
      return;
    }
    socket.addEventListener('open', function () {
      retryDelay = 1000;
      setStatus('Live updates connected');
    });
    socket.addEventListener('message', function (event) {
      var payload;
      try { payload = JSON.parse(String(event.data)); } catch (error) { return; }
      if (!payload || !payload.type) return;
      if (payload.type === '${table}.created' && payload.record) ${varName}s.unshift(payload.record);
      else if (payload.type === '${table}.updated' && payload.record) {
        ${varName}s = ${varName}s.map(function (item) { return item.id === payload.record.id ? payload.record : item; });
      } else if (payload.type === '${table}.deleted') {
        ${varName}s = ${varName}s.filter(function (item) { return item.id !== payload.id; });
      } else return;
      render();
    });
    socket.addEventListener('close', function () {
      setTimeout(function () { retryDelay = Math.min(retryDelay * 2, 30000); connectLive(); }, retryDelay);
    });
    socket.addEventListener('error', function () { setStatus('Live connection error, retrying…', true); });
  }
` : ''}
  document.addEventListener('DOMContentLoaded', function () {
    var form = el('mauli-create-form');
    if (form) form.addEventListener('submit', saveItem);
    var search = el('mauli-search');
    if (search) search.addEventListener('input', render);
    var clear = el('mauli-clear');
    if (clear) clear.addEventListener('click', function () { search.value = ''; render(); });
${auth ? `    var loginForm = el('mauli-login-form');
    if (loginForm) loginForm.addEventListener('submit', login);
    var registerBtn = el('mauli-register');
    if (registerBtn) registerBtn.addEventListener('click', register);
    var logoutBtn = el('mauli-logout');
    if (logoutBtn) logoutBtn.addEventListener('click', logout);
` : ''}    load();
${architecture.realtime ? `    connectLive();` : ''}  });
})();
`;
}

function frontendCss({ label }) {
  return `/* Generated by MAULI 2.0 — styles for ${label}. */
:root {
  --bg: #0d1117;
  --panel: #161b22;
  --line: #26303d;
  --text: #e6edf3;
  --muted: #8b949e;
  --accent: #2f81f7;
  --danger: #f85149;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.5;
  min-height: 100vh;
}
.wrap { max-width: 760px; margin: 0 auto; padding: 32px 20px 64px; }
header h1 { margin: 0; font-size: 1.6rem; letter-spacing: -0.01em; }
.sub { color: var(--muted); margin: 4px 0 20px; font-size: 0.9rem; }
.sub.error, .msg.error { color: var(--danger); }
.card {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 10px;
  padding: 20px;
  margin-bottom: 20px;
}
.card h2 { margin: 0 0 14px; font-size: 1.05rem; }
label { display: block; font-size: 0.82rem; color: var(--muted); margin: 12px 0 4px; }
input, textarea {
  width: 100%;
  padding: 9px 11px;
  border-radius: 6px;
  border: 1px solid var(--line);
  background: #0d1117;
  color: var(--text);
  font-size: 0.95rem;
  font-family: inherit;
}
input:focus, textarea:focus { outline: 2px solid var(--accent); outline-offset: -1px; }
button {
  margin-top: 14px;
  padding: 9px 18px;
  border-radius: 6px;
  border: 1px solid transparent;
  background: var(--accent);
  color: #fff;
  font-weight: 600;
  font-size: 0.92rem;
  cursor: pointer;
}
button:hover { filter: brightness(1.1); }
button.secondary { background: transparent; border-color: var(--line); color: var(--text); }
button.link { background: none; border: none; color: var(--accent); margin: 0 0 0 8px; padding: 4px; }
button.link.danger { color: var(--danger); }
.row { display: flex; gap: 10px; align-items: center; margin-bottom: 12px; }
.row input { flex: 1; }
ul { list-style: none; margin: 0; padding: 0; }
li {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 11px 0;
  border-bottom: 1px solid var(--line);
}
li:last-child { border-bottom: none; }
li .title { flex: 1; font-weight: 500; }
li .meta { color: var(--muted); font-size: 0.82rem; }
.muted { color: var(--muted); }
.msg { min-height: 1.2em; font-size: 0.86rem; margin-top: 8px; }
.who { color: var(--muted); font-size: 0.86rem; }
@media (max-width: 520px) {
  .wrap { padding: 20px 14px 48px; }
  li { flex-wrap: wrap; }
}
`;
}

function wranglerJsonc({ table, realtime, backend = true }) {
  // A browser-only product ships no Worker, so it must declare no `main`: wrangler loads the
  // declared entry point before anything else and refuses to deploy a config whose main is
  // a file that was never generated. The product would have been a website nobody could host.
  return `{
  "name": "generated-${table}-api",${backend ? `
  "main": "worker/index.js",` : ''}
  "compatibility_date": "2026-08-19",
  "compatibility_flags": ["nodejs_compat"],
  "assets": {
    "directory": "./www"${backend ? `,
    "binding": "ASSETS"` : ''}
  },
  "d1_databases": ${backend ? `[
    {
      "binding": "DB",
      "database_name": "generated_${table}",
      "database_id": "replace-with-your-d1-database-id",
      "migrations_dir": "migrations"
    }
  ]` : '[]'}${realtime ? `,
  "durable_objects": {
    "bindings": [{ "name": "LIVE", "class_name": "LiveConnections" }]
  },
  "exports": {
    "LiveConnections": { "type": "durable-object", "storage": "sqlite" }
  }` : ''}
}
`;
}

function readme({ spec, architecture, label, table }) {
  const reqs = (spec.requirements ?? []).map((r) => `- **${r.id}** — ${r.title}`).join('\n');
  return `# ${label}

Generated by MAULI 2.0 from the founder's command:

> ${String(spec.command ?? '').replace(/^/gm, '> ')}

## Architecture

${architecture.layers.map((l) => `- **${l.label}** — ${l.rationale}`).join('\n')}

## Run it

\`\`\`bash
npm install
npx wrangler d1 create generated_${table}     # copy the id into wrangler.jsonc
npx wrangler d1 migrations apply generated_${table} --local
npx wrangler dev                               # serves the frontend AND the Worker API
\`\`\`

The frontend (\`www/\`) is bound as the Worker's static assets and the Worker
(\`worker/index.js\`) serves the API, so one deploy is the whole product. The page calls
\`/api/${table}s\` for every read and write, so there is no second copy of the data in the
browser. The table name is quoted in every statement — \`${table}\` is your own noun, and it
may be a SQL keyword.

## Requirements this build implements

${reqs}
`;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/**
 * Generate the full product the specification asked for.
 * @returns {{files:Array<{path:string,content:string}>, summary:string, table:string,
 *   label:string, architecture:object}}
 */
export function generateFullStackApp(spec, architecture, { objective = '' } = {}) {
  const table = domainEntity(spec);
  const entity = camel(table);
  const label = entityLabel(spec);
  // A browser-only product keeps its records on the device, so the only place its domain
  // can be named is the app itself. The catalogue's generic entity ("entry") gave a founder
  // a medicine tracker whose every identifier said "entry" — the product never said what it
  // was for. The founder's own noun is used instead whenever there is one.
  const localNoun = architecture.backend
    ? null
    : (spec.inferredFromDomain ?? (spec.domainWords ?? []).find((w) => typeof w === 'string' && w.length > 3) ?? null);
  const frontTable = localNoun ?? table;
  const frontEntity = camel(frontTable);
  const frontLabel = localNoun ? frontEntity : label;
  // A browser-only architecture ships no server. Emitting a Worker and a D1 migration for a
  // product that promised to keep its records on the device gave the founder a product whose
  // own documentation contradicted its own code.
  const files = [
    { path: 'www/index.html', content: frontendHtml({ spec, architecture, table: frontTable, entity: frontEntity, label: frontLabel }) },
    { path: 'www/app.js', content: frontendJs({ spec, architecture, table: frontTable, entity: frontEntity, label: frontLabel }) },
    { path: 'www/styles.css', content: frontendCss({ label: frontLabel }) },
    ...(architecture.backend
      ? [
        { path: 'worker/index.js', content: workerSource({ spec, architecture, table, entity, label }) },
        { path: 'migrations/0001_init.sql', content: schemaSql({ table, auth: architecture.auth, realtime: architecture.realtime }) },
        { path: 'wrangler.jsonc', content: wranglerJsonc({ table, realtime: architecture.realtime }) }
      ]
      : [{ path: 'wrangler.jsonc', content: wranglerJsonc({ table: frontTable, realtime: false, backend: false }) }]),
    {
      path: 'package.json',
      content: JSON.stringify({
        name: `generated-${table}`,
        version: '1.0.0',
        private: true,
        type: 'module',
        scripts: {
          dev: 'wrangler dev',
          deploy: 'wrangler deploy',
          'db:migrate:local': `wrangler d1 migrations apply generated_${table} --local`,
          test: 'node --test'
        }
      }, null, 2)
    },
    { path: 'README.md', content: readme({ spec, architecture, label, table }) }
  ];
  return {
    files,
    table,
    api: `/api/${plural(table)}`,
    label,
    architecture,
    summary: `${label} — ${architecture.label}. ${architecture.backend ? 'Worker API over D1' : 'local device store'}${architecture.auth ? ', session-protected' : ''}${architecture.realtime ? ', live updates over WebSocket' : ''}.`,
    tests: [
      'Create a record through the UI and see it in the list',
      'Reload the page and confirm the record is still there',
      ...(architecture.auth ? ['Register, log out, and confirm a protected read is refused while signed out'] : []),
      ...(architecture.realtime ? ['Open two tabs, add a record in one, and see it appear in the other'] : [])
    ],
    notes: [`Generated from ${spec.requirements?.length ?? 0} extracted requirements via ${spec.productType ?? 'generic'} specification.`]
  };
}

export default generateFullStackApp;
