// MAULI 2.0 — spec-driven FULL-STACK generation.
//
// Until now MAULI could only produce a browser page: forms, handlers and localStorage.
// That is a legitimate product for a founder who asked for an offline note pad, and it is
// a fake product for anyone who asked for accounts, shared data or live updates — because
// there was nothing behind the page to talk to.
//
// This generator is deliberately NOT a template library. It is a compiler: it reads the
// founder's extracted specification and emits the architecture that specification selected
// (src/architecture.js) — a real Worker entry point with real D1 SQL, real session
// enforcement, real WebSocket broadcast and a frontend that calls those endpoints. The
// founder's domain nouns become the entity and its columns, so the delivered product is
// the product that was requested rather than whichever sample happened to be nearest.
//
// "Generate less, implement correctly": one deterministic, verified shape beats a page of
// code the runtime then has to prove does nothing.

const ENTITY = 'record';

function pascal(text) {
  return String(text).split(/[^A-Za-z0-9]+/).filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join('') || 'Journey';
}

function singular(word) {
  const w = String(word || 'record').toLowerCase();
  if (/(ies)$/.test(w)) return w.slice(0, -3) + 'y';
  if (/(ses|xes|zes|ches|shes)$/.test(w)) return w.slice(0, -2);
  if (/s$/.test(w) && !/ss$/.test(w)) return w.slice(0, -1);
  return w;
}

function camel(text) {
  const p = pascal(text);
  return p[0].toLowerCase() + p.slice(1);
}

function titleCase(text) {
  return String(text).split(/\s+/).filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
}

/**
 * Did the founder ask for something that happens AT A TIME — a schedule, a due date, a
 * reminder? Read from the features the specification derived, not from the objective's
 * wording, so it stays in step with the requirement the founder can actually contest.
 */
/**
 * Quote a SQL identifier. A founder's product can be called "order", "group" or "user", and
 * every one of those is a SQL keyword: an unquoted CREATE TABLE order is a syntax error that
 * turns every request into a 500, which is exactly what a real deployment reported.
 */
function quoteSql(identifier) {
  return '"' + String(identifier ?? '').replace(/"/g, '""') + '"';
}

function wantsScheduling(spec) {
  return (spec?.features ?? []).some((f) => ['reminder', 'notification'].includes(f?.key));
}

/**
 * Pluralise a record resource the way English does.
 *
 * `/api/entrys` is not a resource, it is a typo that a founder sees in the URL bar and a
 * test cannot guess. `-y` becomes `-ies`; the sibilant endings take `-es`.
 */
function plural(noun) {
  const n = String(noun ?? '');
  if (!n) return n;
  if (/(?:s|x|z|ch|sh)$/i.test(n)) return `${n}es`;
  if (/[^aeiou]y$/i.test(n)) return `${n.slice(0, -1)}ies`;
  if (/[^f]fe$/i.test(n)) return `${n.slice(0, -2)}ves`;
  return `${n}s`;
}

/** The domain noun the founder actually used, used for the entity and its labels. */
export function domainEntity(spec) {
  const words = (spec?.domainWords ?? []).filter((w) => w.length > 2);
  const typeMap = {
    ecommerce: 'order', crm: 'lead', booking: 'booking', inventory: 'item', finance: 'expense',
    health: 'entry', education: 'result', productivity: 'task', dashboard: 'report', automation: 'run'
  };
  if (spec?.productType && typeMap[spec.productType]) return typeMap[spec.productType];
  return singular(words[0] ?? 'record');
}

export function entityLabel(spec) {
  const e = domainEntity(spec);
  return titleCase(e);
}

// ---------------------------------------------------------------------------
// SQL schema
// ---------------------------------------------------------------------------

function schemaSql({ table, auth, realtime, due = false }) {
  const parts = [];
  parts.push(`-- Generated by MAULI 2.0 from the founder's requirement specification.
-- Every table below backs a requirement in the delivered requirement matrix.
CREATE TABLE IF NOT EXISTS ${quoteSql(table)} (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  detail TEXT,
  amount REAL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  owner_email TEXT${due ? ',\n  due TEXT' : ''}
);`);
  if (auth) {
    parts.push(`CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  name TEXT,
  password_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  created_at TEXT NOT NULL
);`);
    parts.push(`CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_email TEXT NOT NULL,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);`);
  }
  if (realtime) {
    parts.push(`CREATE TABLE IF NOT EXISTS rooms (
  id TEXT PRIMARY KEY,
  client_count INTEGER DEFAULT 0
);`);
  }
  return parts.join('\n\n');
}

// ---------------------------------------------------------------------------
// Worker backend
// ---------------------------------------------------------------------------

function workerSource({ spec, architecture, table, entity, label }) {
  const auth = architecture.auth;
  const realtime = architecture.realtime;
  const api = `/api/${plural(table)}`;
  const labelLower = label.toLowerCase();
  // A founder who asked for a schedule, a due date or a reminder asked for a product that
  // stores WHEN something is due. Without the column the derived requirement could never be
  // satisfied, and the delivery gate — correctly — refused to ship it.
  // The INSERT's VALUES list needs a placeholder for the due column, not the column name
  // again: writing the name into VALUES is not valid SQL (a real D1 answers "no such column:
  // due"), while an in-process shim that reads only the column list accepts it. The three
  // emitted constants keep the column list (DUE), the UPDATE assignment (DUE_SET) and the
  // INSERT values (DUE_PLACEHOLDER) distinct.
  const due = wantsScheduling(spec);

  return `// Generated by MAULI 2.0 — Worker backend for ${label}.
// Implements the endpoints the founder's specification requires. Every handler validates,
// talks to D1, and returns a real response; nothing here is faked.

const TABLE = '${table}';
// Quoted: a founder's product can be called "order", and ORDER is a SQL keyword — an
// unquoted CREATE TABLE order is a syntax error, not a table.
const QT = '"' + TABLE + '"';
const SESSION_TTL_MS = 1000 * 60 * 60 * 24 * 7;
const DUE = ${JSON.stringify(due ? ', due' : '')};
const DUE_SET = ${JSON.stringify(due ? ', due = ?' : '')};
const DUE_PLACEHOLDER = ${JSON.stringify(due ? ', ?' : '')};

${auth ? `async function hashPassword(password, salt) {
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(password), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt: new TextEncoder().encode(salt), iterations: 100000, hash: 'SHA-256' },
    key, 256);
  return [...new Uint8Array(bits)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

function newSalt() {
  return [...crypto.getRandomValues(new Uint8Array(16))].map((b) => b.toString(16).padStart(2, '0')).join('');
}
` : ''}
${auth ? `// The session is the only thing that authorises a request. A missing, unknown or
// expired token is refused — never treated as an anonymous read of everyone's data.
async function currentUser(request, env) {
  const header = request.headers.get('Authorization') || '';
  const token = header.replace(/^Bearer\\s+/i, '').trim();
  if (!token) return null;
  const row = await env.DB.prepare('SELECT token, user_email, expires_at FROM sessions WHERE token = ?').bind(token).first();
  if (!row) return null;
  if (new Date(row.expires_at).getTime() < Date.now()) {
    await env.DB.prepare('DELETE FROM sessions WHERE token = ?').bind(token).run();
    return null;
  }
  return { email: row.user_email, token };
}

async function ensureSchema(env) {
  await env.DB.prepare(\`CREATE TABLE IF NOT EXISTS ${quoteSql(table)} (
    id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, detail TEXT,
    amount REAL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, owner_email TEXT\${DUE})\`).run();
${auth ? `  await env.DB.prepare('CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE, name TEXT, password_hash TEXT NOT NULL, salt TEXT NOT NULL, created_at TEXT NOT NULL)').run();
  await env.DB.prepare('CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, user_email TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL)').run();` : ''}
${realtime ? `  await env.DB.prepare('CREATE TABLE IF NOT EXISTS rooms (id TEXT PRIMARY KEY, client_count INTEGER DEFAULT 0)').run();` : ''}
}
` : `async function ensureSchema(env) {
  await env.DB.prepare(\`CREATE TABLE IF NOT EXISTS ${table} (
    id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, detail TEXT,
    amount REAL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, owner_email TEXT)\`).run();
}
`}
function json(data, status = 200, headers = {}) {
  return new Response(JSON.stringify(data), { status, headers: { 'Content-Type': 'application/json', ...headers } });
}

function fail(message, status = 400, details) {
  return json({ ok: false, error: { message, ...(details ? { details } : {}) } }, status);
}

${realtime ? `// Live updates. One WebSocket per connected client; a write broadcasts to every
// OTHER client so the origin's own optimistic update is not duplicated. A client that
// drops is removed, and a client that returns re-subscribes from scratch.
const clients = new Map();

function broadcast(sender, message) {
  let sent = 0;
  for (const [socket, meta] of clients) {
    if (socket === sender) continue;
    try { socket.send(message); sent++; } catch (_) { /* a dead socket is dropped below */ }
  }
  return sent;
}

async function broadcastLive(env, message) {
  if (!env?.LIVE) return 0;
  if (typeof env.LIVE.idFromName === 'function' && typeof env.LIVE.get === 'function') {
    const id = env.LIVE.idFromName('global');
    const stub = env.LIVE.get(id);
    if (typeof stub.broadcast === 'function') return await stub.broadcast(message);
  }
  // Deterministic in-process harness fallback; never used by a real Cloudflare namespace.
  if (typeof env.LIVE.broadcast === 'function') return env.LIVE.broadcast(message);
  return 0;
}
` : ''}
async function route(request, env, url) {
  const path = url.pathname.replace(/\\/+$/, '');
  const method = request.method.toUpperCase();
  await ensureSchema(env);
${auth ? `  const user = await currentUser(request, env);

  if (path === '/api/register' && method === 'POST') {
    const body = await request.json().catch(() => ({}));
    const email = String(body.email ?? '').trim().toLowerCase();
    const password = String(body.password ?? '');
    if (!/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(email)) return fail('A valid email address is required', 422);
    if (password.length < 8) return fail('Password must be at least 8 characters', 422);
    const existing = await env.DB.prepare('SELECT id FROM users WHERE email = ?').bind(email).first();
    if (existing) return fail('That email is already registered', 409);
    const salt = newSalt();
    const hash = await hashPassword(password, salt);
    await env.DB.prepare('INSERT INTO users (email, name, password_hash, salt, created_at) VALUES (?, ?, ?, ?, ?)')
      .bind(email, String(body.name ?? '').trim(), hash, salt, new Date().toISOString()).run();
    return json({ ok: true, email }, 201);
  }

  if (path === '/api/login' && method === 'POST') {
    const body = await request.json().catch(() => ({}));
    const email = String(body.email ?? '').trim().toLowerCase();
    const password = String(body.password ?? '');
    const row = await env.DB.prepare('SELECT email, password_hash, salt FROM users WHERE email = ?').bind(email).first();
    if (!row) return fail('Invalid email or password', 401);
    const hash = await hashPassword(password, row.salt);
    // Constant-time-ish comparison: a mismatch must not be faster than a match.
    const a = Buffer.from(hash);
    const b = Buffer.from(row.password_hash);
    if (a.length !== b.length || !crypto.subtle.timingSafeEqual) {
      if (a.length !== b.length) return fail('Invalid email or password', 401);
    }
    if (hash !== row.password_hash) return fail('Invalid email or password', 401);
    const token = [...crypto.getRandomValues(new Uint8Array(24))].map((b2) => b2.toString(16).padStart(2, '0')).join('');
    const now = Date.now();
    await env.DB.prepare('INSERT INTO sessions (token, user_email, created_at, expires_at) VALUES (?, ?, ?, ?)')
      .bind(token, email, new Date(now).toISOString(), new Date(now + SESSION_TTL_MS).toISOString()).run();
    return json({ ok: true, token, email });
  }

  if (path === '/api/logout' && method === 'POST') {
    if (!user) return fail('Not signed in', 401);
    await env.DB.prepare('DELETE FROM sessions WHERE token = ?').bind(user.token).run();
    return json({ ok: true });
  }

  if (path === '/api/me' && method === 'GET') {
    if (!user) return fail('Not signed in', 401);
    return json({ ok: true, email: user.email });
  }
` : ''}
${auth ? `  if (path.startsWith('/api/') && !path.startsWith('/api/health')) {
    if (!user) return fail('Authentication required', 401);
  }
` : ''}
  if (path === '/api/health' && method === 'GET') {
    // Which bindings this Worker actually received. wrangler reports the bindings it
    // ACCEPTED from the config; this reports the ones that ARRIVED at runtime. The two can
    // differ, and only this one is evidence about the deployed product — a config that
    // declares a Durable Object while the Worker answers 501 has nothing wrong with it that
    // the config could have told you.
    return json({
      ok: true, service: '${label}', time: new Date().toISOString(),
      bindings: {
        database: Boolean(env && env.DB),
        assets: Boolean(env && env.ASSETS),
        live: Boolean(env && env.LIVE)${realtime ? `,
        liveCallable: Boolean(env && env.LIVE && typeof env.LIVE.fetch === 'function')` : ''}
      }
    });
  }

  if (path === '${api}' && method === 'GET') {
    const result = await env.DB.prepare('SELECT id, title, detail, amount, created_at, updated_at' + DUE + ' FROM ' + QT + ' ORDER BY id DESC').all();
    return json({ ok: true, ${table}s: result.results });
  }

  if (path === '${api}' && method === 'POST') {
    const body = await request.json().catch(() => ({}));
    const title = String(body.title ?? '').trim();
    if (!title) return fail('A title is required', 422);
    if (title.length > 200) return fail('Title must be 200 characters or fewer', 422);
    const amount = Number(body.amount ?? 0);
    if (!Number.isFinite(amount) || amount < 0) return fail('Amount must be a positive number', 422);
    const stamp = new Date().toISOString();
    const result = await env.DB.prepare('INSERT INTO ' + QT + ' (title, detail, amount, created_at, updated_at, owner_email' + DUE + ') VALUES (?, ?, ?, ?, ?, ?' + DUE_PLACEHOLDER + ')')
      .bind(title, String(body.detail ?? '').trim(), amount, stamp, stamp${auth ? ', user.email' : ', null'}${due ? ", String(body.due ?? '').trim()" : ''}).run();
    const id = result?.meta?.last_row_id;
    const row = await env.DB.prepare('SELECT id, title, detail, amount, created_at, updated_at' + DUE + ' FROM ' + QT + ' WHERE id = ?').bind(id ?? 0).first();
${realtime ? `    const liveDelivered = await broadcastLive(env, JSON.stringify({ type: '${table}.created', record: row }));` : ''}
    return json({ ok: true, ${table}: row${realtime ? ', liveDelivered' : ''} }, 201);
  }

  const itemMatch = path.match(new RegExp('^' + '${api}' + '/(\\\\d+)$'));
  if (itemMatch) {
    const id = Number(itemMatch[1]);
    if (method === 'GET') {
      const row = await env.DB.prepare('SELECT id, title, detail, amount, created_at, updated_at' + DUE + ' FROM ' + QT + ' WHERE id = ?').bind(id).first();
      if (!row) return fail('${label} not found', 404);
      return json({ ok: true, ${table}: row });
    }
    if (method === 'PUT' || method === 'PATCH') {
      const body = await request.json().catch(() => ({}));
      const title = String(body.title ?? '').trim();
      if (!title) return fail('A title is required', 422);
      const existing = await env.DB.prepare('SELECT id FROM ' + QT + ' WHERE id = ?').bind(id).first();
      if (!existing) return fail('${label} not found', 404);
      const amount = Number(body.amount ?? 0);
      if (!Number.isFinite(amount) || amount < 0) return fail('Amount must be a positive number', 422);
      await env.DB.prepare('UPDATE ' + QT + ' SET title = ?, detail = ?, amount = ?, updated_at = ?' + DUE_SET + ' WHERE id = ?')
        .bind(title, String(body.detail ?? '').trim(), amount, new Date().toISOString()${due ? ", String(body.due ?? '').trim()" : ''}, id).run();
      const row = await env.DB.prepare('SELECT id, title, detail, amount, created_at, updated_at' + DUE + ' FROM ' + QT + ' WHERE id = ?').bind(id).first();
${realtime ? `      await broadcastLive(env, JSON.stringify({ type: '${table}.updated', record: row }));` : ''}
      return json({ ok: true, ${table}: row });
    }
    if (method === 'DELETE') {
      const existing = await env.DB.prepare('SELECT id FROM ' + QT + ' WHERE id = ?').bind(id).first();
      if (!existing) return fail('${label} not found', 404);
      await env.DB.prepare('DELETE FROM ' + QT + ' WHERE id = ?').bind(id).run();
${realtime ? `      await broadcastLive(env, JSON.stringify({ type: '${table}.deleted', id }));` : ''}
      return json({ ok: true, deleted: id });
    }
  }

  return fail('Unknown route: ' + method + ' ' + path, 404);
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    try {
      // Real-time route. The WebSocket handshake and the broadcast fan-out live in the
      // LiveConnections Durable Object. Without this hop the deployed app answers /api/live
      // with a 404 and the live channel silently never connects — while an in-process check
      // that called the class directly still reported the feature as working. The hop is
      // also what makes every client of the product share ONE Durable Object instance, so a
      // write on one client reaches the others.
      if (url.pathname === '/api/live') {
        // Production env.LIVE is a DurableObjectNamespace; resolve a stable instance first.
        if (env && env.LIVE && typeof env.LIVE.idFromName === 'function' && typeof env.LIVE.get === 'function') {
          const id = env.LIVE.idFromName('global');
          return await env.LIVE.get(id).fetch(request);
        }
        // The generated-runtime test harness exposes a direct DO instance for deterministic
        // in-process execution. Production Cloudflare always takes the namespace branch above.
        if (env && env.LIVE && typeof env.LIVE.fetch === 'function') return await env.LIVE.fetch(request, env);
        return fail('Live updates are not configured for this deployment', 501);
      }
      return await route(request, env, url);
    } catch (error) {
      // An unexpected failure is reported as a failure. It is never converted into a
      // success shape — that is how a broken product reaches a founder looking finished.
      return fail('Server error: ' + (error && error.message ? error.message : String(error)), 500);
    }
  }
};
${realtime ? `
// Real-time entry point: upgrade a request to a WebSocket and keep it in the client set.
//
// It extends DurableObject because the config declares this class as a SQLite-backed
// Durable Object (\`new_sqlite_classes\`). A class that does not extend the runtime base is
// not a Durable Object to workerd: the deploy SUCCEEDS, wrangler's dry run reports
// \`env.LIVE\` as a bound Durable Object, and at runtime the binding is simply absent -- the
// deployed app then answers /api/live with 501 while every configuration check passes.
import { DurableObject } from 'cloudflare:workers';

export class LiveConnections extends DurableObject {
  constructor(ctx, state) {
    // Only the client set is kept: this Durable Object holds connections, not rows, so
    // there is no storage to read, and an unused \`this.state\` would be dead code.
    super(ctx, state);
    this.clients = new Set();
  }
  broadcast(message, sender = null) {
    let delivered = 0;
    for (const socket of this.clients) {
      if (socket === sender) continue;
      try { socket.send(message); delivered++; } catch (_) { this.clients.delete(socket); }
    }
    return delivered;
  }
  async fetch(request) {
    const pathname = new URL(request.url).pathname;
    if (pathname !== '/api/live') return new Response('Not found', { status: 404 });
    if (request.headers.get('Upgrade') !== 'websocket') return new Response('Expected a WebSocket upgrade', { status: 426 });
    const pair = new WebSocketPair();
    const client = pair[0];
    const server = pair[1];
    server.accept();
    this.clients.add(server);
    server.addEventListener('message', (event) => {
      let payload;
      try { payload = JSON.parse(String(event.data)); } catch (_) { return; }
      if (payload && payload.type === 'ping') this.broadcast(JSON.stringify({ type: 'pong', at: Date.now() }), server);
    });
    server.addEventListener('close', () => { this.clients.delete(server); });
    server.addEventListener('error', () => { this.clients.delete(server); });
    // Confirm the connection from the SERVER side. A client that merely completed the
    // handshake has proven the socket opened, not that this Durable Object accepted it and
    // will broadcast to it -- and those are different failures. Without this confirmation a
    // channel that accepts the upgrade and then delivers nothing looks connected.
    try { server.send(JSON.stringify({ type: 'connected', at: Date.now() })); } catch (_) { /* the client vanished immediately */ }
    return new Response(null, { status: 101, webSocket: client });
  }
}
` : ''}
`;
}

// ---------------------------------------------------------------------------
// Frontend
// ---------------------------------------------------------------------------

// The product's pages. Every page is a REAL file under www/, and every page carries the
// same navigation — a nav link that points at a file the product does not ship is a button
// that opens nothing, which is exactly how a founder ends up with a "second page that does
// not open". src/generated-app-quality.js refuses that shape.
const PAGES = [
  { key: 'dashboard', file: 'index.html', label: 'Dashboard', icon: 'grid' },
  { key: 'reports', file: 'reports.html', label: 'Reports', icon: 'chart' },
  { key: 'settings', file: 'settings.html', label: 'Settings', icon: 'gear' }
];

// Inline SVG artwork. Every graphic the product draws ships inside the page: an <img> that
// points at a file the generator never emitted is a broken product, and an icon CDN is a
// network dependency that fails silently. One inline file always resolves and always paints.
const ICONS = {
  grid: '<rect x="3" y="3" width="7.5" height="7.5" rx="2"/><rect x="13.5" y="3" width="7.5" height="7.5" rx="2"/><rect x="3" y="13.5" width="7.5" height="7.5" rx="2"/><rect x="13.5" y="13.5" width="7.5" height="7.5" rx="2"/>',
  chart: '<path d="M4 20V11"/><path d="M10 20V4"/><path d="M16 20v-6"/><path d="M22 20H2"/>',
  gear: '<circle cx="12" cy="12" r="3.2"/><path d="M12 2.5v2.8M12 18.7v2.8M2.5 12h2.8M18.7 12h2.8M5.3 5.3l2 2M16.7 16.7l2 2M18.7 5.3l-2 2M7.3 16.7l-2 2"/>',
  plus: '<path d="M12 5v14M5 12h14"/>',
  search: '<circle cx="11" cy="11" r="6.5"/><path d="M20 20l-3.6-3.6"/>',
  edit: '<path d="M4 20.5h4.5L20 9l-4.5-4.5L4 16v4.5z"/><path d="M14 6l4 4"/>',
  trash: '<path d="M4 7h16M9.5 7V4.5h5V7M6.5 7l1 12.5h9L17.5 7"/>',
  download: '<path d="M12 3.5v11M7.5 10.5l4.5 4.5 4.5-4.5M4 20.5h16"/>',
  logout: '<path d="M14.5 4.5H19v15h-4.5M10.5 8L6.5 12l4 4M6.5 12h9"/>',
  signin: '<path d="M9.5 4.5H5v15h4.5M14 8.5l3.5 3.5-3.5 3.5M17 12H9"/>',
  shield: '<path d="M12 3l7 2.5v5.5c0 4-3 7.5-7 9-4-1.5-7-5-7-9V5.5L12 3z"/><path d="M9 12l2 2 4-4"/>',
  user: '<circle cx="12" cy="8.5" r="3.5"/><path d="M4.5 20.5c0-4 3.4-6.5 7.5-6.5s7.5 2.5 7.5 6.5"/>',
  layers: '<path d="M12 3l8.5 4.5L12 12 3.5 7.5 12 3z"/><path d="M3.5 12.5L12 17l8.5-4.5"/>',
  spark: '<path d="M12 3.2l1.9 5.4 5.4 1.9-5.4 1.9L12 17.8l-1.9-5.4L4.7 10.5l5.4-1.9L12 3.2z"/>',
  wallet: '<path d="M3.5 7.5A2.5 2.5 0 016 5h11.5a2 2 0 012 2v1.5"/><rect x="3.5" y="7.5" width="17" height="11.5" rx="2.5"/><circle cx="16.5" cy="13" r="1.2"/>',
  clock: '<circle cx="12" cy="12" r="8.5"/><path d="M12 7.5V12l3 2"/>'
};

function icon(name, cls) {
  const body = ICONS[name] ?? ICONS.spark;
  return `<svg class="icon${cls ? ' ' + cls : ''}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false">${body}</svg>`;
}

function logoMark() {
  return '<svg class="mark" viewBox="0 0 40 40" aria-hidden="true" focusable="false">' +
    '<defs><linearGradient id="mauli-g" x1="0" y1="0" x2="1" y2="1">' +
    '<stop offset="0" stop-color="var(--accent)"/><stop offset="1" stop-color="var(--accent-2)"/></linearGradient></defs>' +
    '<rect x="1" y="1" width="38" height="38" rx="12" fill="url(#mauli-g)"/>' +
    '<path d="M12.5 28V12.5h7.5a5 5 0 010 10h-4.2l6.7 5.5" stroke="#fff" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/></svg>';
}

/**
 * A stable accent hue per product, so two generated products never look like the same
 * template with a different noun in it.
 */
function accentFor(label) {
  let h = 0;
  for (const ch of String(label ?? '')) h = (h * 31 + ch.codePointAt(0)) % 360;
  return h;
}

function navHtml(page, label) {
  const links = PAGES.map((p) => {
    const active = p.key === page;
    return `        <a class="nav-link${active ? ' active' : ''}" href="${p.file}"${active ? ' aria-current="page"' : ''}>${icon(p.icon)}<span>${p.label}</span></a>`;
  }).join('\n');
  return `  <aside class="sidebar">
    <a class="brand" href="index.html">
      ${logoMark()}
      <span class="brand-text"><strong>${label}</strong><small>${page === 'reports' ? 'Reports' : (page === 'settings' ? 'Settings' : 'Overview')}</small></span>
    </a>
    <nav class="nav" aria-label="Main navigation">
${links}
    </nav>
    <div class="sidebar-foot">
      <span class="pulse" aria-hidden="true"></span>
      <span>Live data &middot; no sample rows</span>
    </div>
  </aside>`;
}

function frontendHtml({ spec, architecture, table, entity, label, page = 'dashboard' }) {
  const auth = architecture.auth;
  // The account card sits on EVERY page: a founder who lands on Reports first must be able
  // to sign in there instead of being told, on a page with no login form, to go elsewhere.
  const authBlock = auth ? `
      <section id="mauli-auth" class="card auth">
        <div class="card-head">
          <h2>Account</h2>
          ${icon('user', 'card-icon')}
        </div>
        <div id="mauli-auth-msg" class="msg" role="status"></div>
        <form id="mauli-login-form">
          <label for="mauli-login-email">Email</label>
          <input id="mauli-login-email" type="email" autocomplete="email" required>
          <label for="mauli-login-password">Password</label>
          <input id="mauli-login-password" type="password" autocomplete="current-password" required>
          <div class="btn-row">
            <button type="submit" id="mauli-login">${icon('signin', 'btn-icon')}Log in</button>
            <button type="button" id="mauli-register" class="secondary">Create account</button>
          </div>
        </form>
        <button type="button" id="mauli-logout" class="secondary full" hidden>${icon('logout', 'btn-icon')}Log out</button>
        <p class="who" id="mauli-who"></p>
      </section>` : '';

  const dashboardBody = `
  <section class="card stats-card">
    <div class="card-head">
      <h2>Overview</h2>
      <span class="tag">Live</span>
    </div>
    <div id="mauli-stats" class="stats"></div>
    <div id="mauli-chart" class="chart" role="img" aria-label="Activity over the last 14 days"></div>
  </section>
${authBlock}
  <div class="cols">
  <section class="card">
    <div class="card-head">
      <h2>Add a ${entity}</h2>
      ${icon('plus', 'card-icon')}
    </div>
    <form id="mauli-create-form">
      <label for="mauli-title">Title</label>
      <input id="mauli-title" name="title" required maxlength="200">
      <label for="mauli-due">Scheduled for</label>
      <input id="mauli-due" name="due" type="date">
      <label for="mauli-amount">Amount</label>
      <input id="mauli-amount" name="amount" type="number" min="0" step="0.01" value="0">
      <label for="mauli-detail">Details</label>
      <textarea id="mauli-detail" name="detail" rows="3"></textarea>
      <button type="submit" id="mauli-save">${icon('plus', 'btn-icon')}Save ${entity}</button>
    </form>
    <div id="mauli-error" class="msg error" role="alert"></div>
  </section>
  <section class="card list-card">
    <div class="card-head">
      <h2>All ${table}s</h2>
      <span class="count" id="mauli-count">0</span>
    </div>
    <div class="row search-row">
      <span class="search-icon">${icon('search')}</span>
      <input id="mauli-search" type="search" placeholder="Search ${table}s" aria-label="Search ${table}s">
      <button type="button" id="mauli-clear" class="secondary">Clear</button>
    </div>
    <ul id="mauli-list"></ul>
    <div id="mauli-empty" class="empty">
      ${icon('layers', 'empty-icon')}
      <p>No ${table}s yet.</p>
      <p class="muted">Add your first ${entity} and it appears here instantly.</p>
    </div>
  </section>
  </div>`;

  const reportsBody = `
${authBlock}
  <section class="card">
    <div class="card-head">
      <h2>Reports</h2>
      ${icon('chart', 'card-icon')}
    </div>
    <p class="sub">Live totals computed from the same data the Dashboard stores — no second copy.</p>
    <div id="mauli-report" class="report"><p class="muted">Loading&hellip;</p></div>
  </section>`;

  const settingsBody = `
${authBlock}
  <section class="card">
    <div class="card-head">
      <h2>Your data</h2>
      ${icon('download', 'card-icon')}
    </div>
    <p class="muted">Take everything with you: exports every ${entity} as a JSON file.</p>
    <button type="button" id="mauli-export">${icon('download', 'btn-icon')}Export data (JSON)</button>
    <div id="mauli-settings-msg" class="msg" role="status"></div>
  </section>
  <section class="card">
    <div class="card-head">
      <h2>About</h2>
      ${icon('spark', 'card-icon')}
    </div>
    <p class="muted">${label} — built by MAULI 2.0 on the ${architecture.label}.</p>
    <ul class="facts">
      <li>${icon('layers')}<span>Storage: ${architecture.backend ? 'Cloudflare D1 + Worker API' : 'this device'}</span></li>
      <li>${icon('user')}<span>Accounts: ${architecture.auth ? 'email and password' : 'single workspace'}</span></li>
      <li>${icon('clock')}<span>Live updates: ${architecture.realtime ? 'WebSocket broadcast' : 'on every load'}</span></li>
    </ul>
  </section>`;

  const body = page === 'reports' ? reportsBody : (page === 'settings' ? settingsBody : dashboardBody);
  const headings = {
    dashboard: ['Dashboard', 'Everything below is live — it reads and writes the real store.'],
    reports: ['Reports', `Totals, activity and the latest ${table}s at a glance.`],
    settings: ['Settings', `Account and data controls for ${label}.`]
  };
  const [heading, sub] = headings[page] ?? headings.dashboard;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="${label} — ${sub}">
<title>${heading} · ${label}</title>
<link rel="stylesheet" href="styles.css">
</head>
<body>
<div class="glow" aria-hidden="true"></div>
<div class="shell">
${navHtml(page, label)}
  <main class="main">
  <header class="hero">
    <div class="hero-text">
      <span class="eyebrow">${icon('spark')} ${label}</span>
      <h1>${heading}</h1>
      <p class="sub" id="mauli-status">${sub}</p>
    </div>
    <div class="hero-art" aria-hidden="true">${icon(page === 'reports' ? 'chart' : (page === 'settings' ? 'gear' : 'layers'), 'hero-icon')}</div>
  </header>
${body}
  </main>
</div>
<script src="app.js"></script>
</body>
</html>
`;
}

function frontendJs({ spec, architecture, table, entity, label }) {
  const auth = architecture.auth;
  const api = `/api/${plural(table)}`;
  const varName = camel(table);
  return `// Generated by MAULI 2.0 — frontend for ${label}.
// Every control below calls the real backend. There is no local fallback store: if the
// API is down the UI says so, because a client that quietly reports success without a
// server is not the product the founder commissioned.
(function () {
  'use strict';

  var API = '${api}';
  var TOKEN_KEY = '${table}.session';
  var ${varName}s = [];
  var socket = null;

  function el(id) { return document.getElementById(id); }

  function token() { return window.localStorage.getItem(TOKEN_KEY); }

  function setToken(value) {
    if (value) window.localStorage.setItem(TOKEN_KEY, value);
    else window.localStorage.removeItem(TOKEN_KEY);
  }

  function setStatus(message, isError) {
    var node = el('mauli-status');
    if (node) { node.textContent = message; node.className = isError ? 'sub error' : 'sub'; }
  }

  function showError(message) {
    var node = el('mauli-error');
    if (node) node.textContent = message;
    var auth = el('mauli-auth-msg');
    if (auth) auth.textContent = message;
  }

  // One place where every backend call happens, so error handling and the session header
  // cannot drift between features.
  //
  // A browser-only architecture has NO server to call. Emitting the same fetch-based client
  // anyway produced a product that described itself as a local device store while every one
  // of its reads and writes pointed at an /api endpoint that does not exist — so the UI never
  // changed state and the product failed its own runtime bar. The local adapter answers the
  // SAME routes from the device store, which is what this architecture actually owes.
  function api(method, path, body) {
${architecture.backend ? `    var headers = { 'Content-Type': 'application/json' };
    var current = token();
    if (current) headers.Authorization = 'Bearer ' + current;
    var options = { method: method, headers: headers };
    if (body !== undefined) options.body = JSON.stringify(body);
    return fetch(path, options).then(function (response) {
      return response.json().catch(function () { return {}; }).then(function (payload) {
        if (!response.ok) {
          var error = new Error((payload && payload.error && payload.error.message) || ('Request failed with ' + response.status));
          error.status = response.status;
          throw error;
        }
        return payload;
      });
    });` : `    var rows = readStore();
    var match = path.match(new RegExp('^${api}/(\\\\d+)$'));
    if (method === 'GET' && !match) return Promise.resolve({ ok: true, ${table}s: rows });
    if (method === 'POST') {
      var title = String((body && body.title) || '').trim();
      if (!title) return Promise.reject(new Error('A title is required'));
      var stamp = new Date().toISOString();
      var record = { id: rows.length + 1, title: title, detail: String((body && body.detail) || ''), amount: Number((body && body.amount) || 0), created_at: stamp, updated_at: stamp };
      rows.push(record);
      writeStore(rows);
      return Promise.resolve({ ok: true, ${table}: record });
    }
    if (match) {
      var id = Number(match[1]);
      var at = -1;
      for (var i = 0; i < rows.length; i += 1) { if (Number(rows[i].id) === id) { at = i; break; } }
      if (at < 0) return Promise.reject(new Error('${label} not found'));
      if (method === 'GET') return Promise.resolve({ ok: true, ${table}: rows[at] });
      if (method === 'PUT' || method === 'PATCH') {
        var title = String((body && body.title) || '').trim();
        if (!title) return Promise.reject(new Error('A title is required'));
        rows[at].title = title;
        rows[at].detail = String((body && body.detail) || '');
        rows[at].updated_at = new Date().toISOString();
        writeStore(rows);
        return Promise.resolve({ ok: true, ${table}: rows[at] });
      }
      if (method === 'DELETE') { rows.splice(at, 1); writeStore(rows); return Promise.resolve({ ok: true, deleted: id }); }
    }
    return Promise.reject(new Error('Unknown route: ' + method + ' ' + path));`}
  }

${architecture.backend ? '' : `  // The device store. Records written here survive a reload — that persistence is what
  // a browser-only product owes, and it is what its runtime evidence has to show.
  var STORE_KEY = '${table}.records';
  function readStore() {
    try { var raw = window.localStorage.getItem(STORE_KEY); var rows = raw ? JSON.parse(raw) : []; return Array.isArray(rows) ? rows : []; }
    catch (_) { return []; }
  }
  function writeStore(rows) { window.localStorage.setItem(STORE_KEY, JSON.stringify(rows)); }
`}

  function render() {
    var list = el('mauli-list');
    if (list) {
      var query = (el('mauli-search') && el('mauli-search').value || '').trim().toLowerCase();
      var visible = ${varName}s.filter(function (item) {
        if (!query) return true;
        return String(item.title || '').toLowerCase().indexOf(query) !== -1
          || String(item.detail || '').toLowerCase().indexOf(query) !== -1;
      });
      list.innerHTML = '';
      visible.forEach(function (item) {
        var li = document.createElement('li');
        li.setAttribute('data-id', String(item.id));
        li.className = 'row-item';
        var badge = document.createElement('span');
        badge.className = 'avatar';
        badge.setAttribute('aria-hidden', 'true');
        badge.textContent = initials(item.title);
        var body = document.createElement('div');
        body.className = 'row-body';
        var title = document.createElement('span');
        title.className = 'title';
        title.textContent = item.title;
        var meta = document.createElement('span');
        meta.className = 'meta';
        meta.textContent = String(item.created_at || '').slice(0, 10) + (item.due ? ' · due ' + String(item.due).slice(0, 10) : '');
        body.appendChild(title);
        body.appendChild(meta);
        var amount = document.createElement('span');
        amount.className = 'amount';
        amount.textContent = Number(item.amount || 0).toFixed(2);
        var actions = document.createElement('span');
        actions.className = 'actions';
        var edit = document.createElement('button');
        edit.type = 'button';
        edit.className = 'icon-btn';
        edit.title = 'Edit';
        edit.setAttribute('aria-label', 'Edit ' + item.title);
        edit.textContent = '\u270E';
        edit.addEventListener('click', function () { startEdit(item); });
        var remove = document.createElement('button');
        remove.type = 'button';
        remove.className = 'icon-btn danger';
        remove.title = 'Delete';
        remove.setAttribute('aria-label', 'Delete ' + item.title);
        remove.textContent = '\u2715';
        remove.addEventListener('click', function () { removeItem(item.id); });
        actions.appendChild(edit);
        actions.appendChild(remove);
        li.appendChild(badge);
        li.appendChild(body);
        li.appendChild(amount);
        li.appendChild(actions);
        list.appendChild(li);
      });
      var empty = el('mauli-empty');
      if (empty) empty.hidden = visible.length > 0;
      var count = el('mauli-count');
      if (count) count.textContent = String(visible.length);
    }
    // Every page renders from the same loaded data: the Dashboard's overview cards, the
    // Reports page's totals, and the list itself. A page that has none of those elements
    // simply has nothing to draw here.
    renderStats();
    renderChart();
    renderReport();
  }

  function initials(text) {
    var parts = String(text || '?').trim().split(/\\s+/).slice(0, 2);
    return parts.map(function (word) { return word.charAt(0).toUpperCase(); }).join('') || '?';
  }

  function statCard(labelText, valueText, iconName, tone) {
    var card = document.createElement('div');
    card.className = 'stat' + (tone ? ' tone-' + tone : '');
    var head = document.createElement('div');
    head.className = 'stat-top';
    var name = document.createElement('span');
    name.className = 'stat-k';
    name.textContent = labelText;
    head.appendChild(name);
    var value = document.createElement('span');
    value.className = 'stat-v';
    value.textContent = valueText;
    card.appendChild(head);
    card.appendChild(value);
    if (iconName) card.setAttribute('data-icon', iconName);
    return card;
  }

  // The chart is drawn from the same loaded rows as every other number on the page: one
  // bar per day for the last 14 days, height proportional to what was added that day. A
  // decorative graphic that did not read the data would be a picture of a dashboard.
  function renderChart() {
    var box = el('mauli-chart');
    if (!box) return;
    var days = 14;
    var today = new Date();
    var buckets = [];
    var i;
    for (i = days - 1; i >= 0; i -= 1) {
      var day = new Date(today.getTime() - i * 86400000);
      buckets.push({ key: day.toISOString().slice(0, 10), count: 0, total: 0 });
    }
    var index = {};
    buckets.forEach(function (bucket) { index[bucket.key] = bucket; });
    ${varName}s.forEach(function (item) {
      var key = String(item.created_at || '').slice(0, 10);
      if (index[key]) {
        index[key].count += 1;
        index[key].total += Number(item.amount) || 0;
      }
    });
    var peak = buckets.reduce(function (max, bucket) { return Math.max(max, bucket.total); }, 0);
    // A product whose rows carry no amounts would draw fourteen identical stubs. When
    // there is nothing to total, the chart falls back to the count it really has.
    var useCount = peak <= 0;
    if (useCount) peak = buckets.reduce(function (max, bucket) { return Math.max(max, bucket.count); }, 0);
    var bars = buckets.map(function (bucket) {
      var value = useCount ? bucket.count : bucket.total;
      var height = peak > 0 ? Math.max(4, Math.round((value / peak) * 100)) : 4;
      var caption = useCount ? (bucket.count + ' added') : bucket.total.toFixed(2);
      return '<div class="bar" style="height:' + height + '%" title="' + bucket.key + ': ' + caption + '"></div>';
    }).join('');
    box.innerHTML = bars + '<div class="chart-base"></div>';
  }

  function totals() {
    var amount = 0;
    var latest = '';
    var today = new Date().toISOString().slice(0, 10);
    var addedToday = 0;
    ${varName}s.forEach(function (item) {
      amount += Number(item.amount) || 0;
      var created = String(item.created_at || '').slice(0, 10);
      var updated = String(item.updated_at || '');
      if (updated > latest) latest = updated;
      if (created === today) addedToday += 1;
    });
    return { count: ${varName}s.length, amount: amount, latest: latest, addedToday: addedToday };
  }

  function renderStats() {
    var box = el('mauli-stats');
    if (!box) return;
    var t = totals();
    box.innerHTML = '';
    box.appendChild(statCard('Total ${table}s', String(t.count), 'layers', 'a'));
    box.appendChild(statCard('Added today', String(t.addedToday), 'spark', 'b'));
    box.appendChild(statCard('Total amount', t.amount.toFixed(2), 'wallet', 'c'));
    box.appendChild(statCard('Last activity', t.latest ? t.latest.slice(0, 10) : '—', 'clock', 'd'));
  }

  function renderReport() {
    var box = el('mauli-report');
    if (!box) return;
    var t = totals();
    box.innerHTML = '';
    var summary = document.createElement('div');
    summary.className = 'stats';
    summary.appendChild(statCard('Total ${table}s', String(t.count), 'layers', 'a'));
    summary.appendChild(statCard('Total amount', t.amount.toFixed(2), 'wallet', 'c'));
    summary.appendChild(statCard('Last activity', t.latest ? t.latest.slice(0, 16).replace('T', ' ') : '—', 'clock', 'd'));
    box.appendChild(summary);
    if (!t.count) {
      var none = document.createElement('p');
      none.className = 'muted';
      none.textContent = 'No ${table}s yet — add one from the Dashboard.';
      box.appendChild(none);
      return;
    }
    var table = document.createElement('table');
    table.className = 'tbl';
    var head = document.createElement('thead');
    var headRow = document.createElement('tr');
    ['Title', 'Amount', 'Created'].forEach(function (labelText) {
      var th = document.createElement('th');
      th.textContent = labelText;
      headRow.appendChild(th);
    });
    head.appendChild(headRow);
    table.appendChild(head);
    var bodyEl = document.createElement('tbody');
    ${varName}s.slice(0, 20).forEach(function (item) {
      var row = document.createElement('tr');
      var title = document.createElement('td');
      title.textContent = item.title || '';
      var amount = document.createElement('td');
      amount.textContent = Number(item.amount || 0).toFixed(2);
      var created = document.createElement('td');
      created.textContent = String(item.created_at || '').slice(0, 10);
      row.appendChild(title);
      row.appendChild(amount);
      row.appendChild(created);
      bodyEl.appendChild(row);
    });
    table.appendChild(bodyEl);
    box.appendChild(table);
  }

  // The Settings page's export is a real download of the real data — no server needed,
  // and it refuses to pretend: an empty list exports an empty file with an honest count.
  function exportRecords() {
    var msg = el('mauli-settings-msg');
    try {
      var payload = JSON.stringify({ exportedAt: new Date().toISOString(), count: ${varName}s.length, records: ${varName}s }, null, 2);
      var blob = new Blob([payload], { type: 'application/json' });
      var url = URL.createObjectURL(blob);
      var a = document.createElement('a');
      a.href = url;
      a.download = '${table}-export.json';
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(function () { URL.revokeObjectURL(url); }, 5000);
      if (msg) msg.textContent = 'Exported ' + ${varName}s.length + ' ${table}(s)';
    } catch (error) {
      if (msg) msg.textContent = 'Export failed: ' + error.message;
    }
  }

  var editingId = null;

  function startEdit(item) {
    editingId = item.id;
    el('mauli-title').value = item.title || '';
    el('mauli-detail').value = item.detail || '';
    if (el('mauli-due')) el('mauli-due').value = item.due || '';
    el('mauli-amount').value = item.amount != null ? item.amount : 0;
    el('mauli-save').textContent = 'Update';
    el('mauli-title').focus();
  }

  function resetForm() {
    editingId = null;
    el('mauli-title').value = '';
    el('mauli-detail').value = '';
    if (el('mauli-due')) el('mauli-due').value = '';
    el('mauli-amount').value = '0';
    el('mauli-save').textContent = 'Save';
  }

  function load() {
    return api('GET', API).then(function (payload) {
      ${varName}s = payload.${table}s || [];
      render();
      setStatus(${varName}s.length + ' ${table}(s) loaded from the database');
    }).catch(function (error) {
      if (error.status === 401) {
        ${varName}s = [];
        render();
        setStatus('Please log in to see your ${table}s', true);
        return;
      }
      setStatus('Could not reach the server: ' + error.message, true);
    });
  }

  function saveItem(event) {
    if (event && event.preventDefault) event.preventDefault();
    showError('');
    var payload = {
      title: el('mauli-title').value.trim(),
      due: el('mauli-due') ? el('mauli-due').value : '',
      detail: el('mauli-detail').value.trim(),
      amount: Number(el('mauli-amount').value || 0)
    };
    var request = editingId
      ? api('PUT', API + '/' + editingId, payload)
      : api('POST', API, payload);
    return request.then(function (result) {
      var saved = result.${table};
      if (editingId) {
        ${varName}s = ${varName}s.map(function (item) { return item.id === saved.id ? saved : item; });
      } else {
        ${varName}s.unshift(saved);
      }
      render();
      resetForm();
      setStatus('Saved “' + saved.title + '”');
    }).catch(function (error) {
      showError(error.message);
      setStatus('Not saved: ' + error.message, true);
    });
  }

  function removeItem(id) {
    showError('');
    return api('DELETE', API + '/' + id).then(function () {
      ${varName}s = ${varName}s.filter(function (item) { return item.id !== id; });
      render();
      setStatus('Deleted');
    }).catch(function (error) {
      showError(error.message);
    });
  }
${auth ? `
  function showSignedIn(email) {
    var logout = el('mauli-logout');
    if (logout) logout.hidden = false;
    var login = el('mauli-login');
    if (login) login.hidden = true;
    var who = el('mauli-who');
    if (who) who.textContent = 'Signed in as ' + email;
    var status = el('mauli-status');
    if (status) status.className = 'sub';
  }

  function showSignedOut() {
    var logout = el('mauli-logout');
    if (logout) logout.hidden = true;
    var login = el('mauli-login');
    if (login) login.hidden = false;
    var who = el('mauli-who');
    if (who) who.textContent = '';
  }

  function credentials() {
    return {
      email: el('mauli-login-email').value.trim(),
      password: el('mauli-login-password').value,
      name: el('mauli-login-email').value.trim()
    };
  }

  function login(event) {
    if (event && event.preventDefault) event.preventDefault();
    showError('');
    return api('POST', '/api/login', credentials()).then(function (payload) {
      setToken(payload.token);
      showSignedIn(payload.email);
      el('mauli-login-password').value = '';
      return load();
    }).catch(function (error) { showError(error.message); });
  }

  function register() {
    showError('');
    return api('POST', '/api/register', credentials()).then(function () {
      return api('POST', '/api/login', credentials());
    }).then(function (payload) {
      setToken(payload.token);
      showSignedIn(payload.email);
      return load();
    }).catch(function (error) { showError(error.message); });
  }

  function logout() {
    return api('POST', '/api/logout').then(function () {
      setToken(null);
      ${varName}s = [];
      render();
      showSignedOut();
      setStatus('Signed out');
    }).catch(function (error) { showError(error.message); });
  }
` : ''}${architecture.realtime ? `
  // Live updates from the server. Reconnect is deliberate and bounded: a dropped
  // connection retries with a growing delay and re-reads the list when it comes back, so
  // a client is never left showing stale data after a disconnect.
  var retryDelay = 1000;

  function connectLive() {
    var protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    try {
      socket = new WebSocket(protocol + '//' + window.location.host + '/api/live');
    } catch (error) {
      setStatus('Live updates unavailable: ' + error.message, true);
      return;
    }
    socket.addEventListener('open', function () {
      retryDelay = 1000;
      setStatus('Live updates connected');
    });
    socket.addEventListener('message', function (event) {
      var payload;
      try { payload = JSON.parse(String(event.data)); } catch (error) { return; }
      if (!payload || !payload.type) return;
      if (payload.type === '${table}.created' && payload.record) ${varName}s.unshift(payload.record);
      else if (payload.type === '${table}.updated' && payload.record) {
        ${varName}s = ${varName}s.map(function (item) { return item.id === payload.record.id ? payload.record : item; });
      } else if (payload.type === '${table}.deleted') {
        ${varName}s = ${varName}s.filter(function (item) { return item.id !== payload.id; });
      } else return;
      render();
    });
    socket.addEventListener('close', function () {
      setTimeout(function () { retryDelay = Math.min(retryDelay * 2, 30000); connectLive(); }, retryDelay);
    });
    socket.addEventListener('error', function () { setStatus('Live connection error, retrying…', true); });
  }
` : ''}
  document.addEventListener('DOMContentLoaded', function () {
    var form = el('mauli-create-form');
    if (form) form.addEventListener('submit', saveItem);
    var search = el('mauli-search');
    if (search) search.addEventListener('input', render);
    var clear = el('mauli-clear');
    if (clear) clear.addEventListener('click', function () { search.value = ''; render(); });
    var exportBtn = el('mauli-export');
    if (exportBtn) exportBtn.addEventListener('click', exportRecords);
${auth ? `    var loginForm = el('mauli-login-form');
    if (loginForm) loginForm.addEventListener('submit', login);
    var registerBtn = el('mauli-register');
    if (registerBtn) registerBtn.addEventListener('click', register);
    var logoutBtn = el('mauli-logout');
    if (logoutBtn) logoutBtn.addEventListener('click', logout);
` : ''}    load();
${architecture.realtime ? `    connectLive();` : ''}  });
})();
`;
}

function frontendCss({ label, hue = 250 }) {
  return `/* Generated by MAULI 2.0 — styles for ${label}. */
:root {
  --bg: #070b16;
  --bg-2: #0b1222;
  --panel: rgba(19, 26, 45, 0.82);
  --panel-solid: #131a2d;
  --line: rgba(255, 255, 255, 0.09);
  --line-strong: rgba(255, 255, 255, 0.16);
  --text: #eef2ff;
  --muted: #97a3c0;
  --accent: hsl(${hue} 92% 66%);
  --accent-2: hsl(${(hue + 58) % 360} 90% 62%);
  --accent-soft: hsl(${hue} 92% 66% / 0.14);
  --danger: #ff6b81;
  --ok: #4ade80;
  --radius: 18px;
  --radius-sm: 12px;
  --shadow: 0 18px 40px rgba(2, 6, 23, 0.55);
  --ease: cubic-bezier(0.22, 1, 0.36, 1);
}
* { box-sizing: border-box; }
html { -webkit-text-size-adjust: 100%; }
body {
  margin: 0;
  min-height: 100vh;
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
  background: radial-gradient(1200px 700px at 12% -10%, hsl(${hue} 90% 40% / 0.28), transparent 60%),
              radial-gradient(900px 600px at 105% 0%, hsl(${(hue + 70) % 360} 88% 44% / 0.22), transparent 55%),
              var(--bg);
  background-attachment: fixed;
  color: var(--text);
  line-height: 1.55;
  -webkit-font-smoothing: antialiased;
}
.glow {
  position: fixed;
  inset: 0;
  pointer-events: none;
  background: radial-gradient(600px 300px at 50% 0%, hsl(${hue} 95% 60% / 0.12), transparent 70%);
  z-index: 0;
}
.shell {
  position: relative;
  z-index: 1;
  display: grid;
  grid-template-columns: 264px minmax(0, 1fr);
  gap: 28px;
  max-width: 1220px;
  margin: 0 auto;
  padding: 28px 24px 72px;
}

/* ---- sidebar ---- */
.sidebar {
  position: sticky;
  top: 28px;
  align-self: start;
  display: flex;
  flex-direction: column;
  gap: 22px;
  padding: 22px 16px;
  background: var(--panel);
  backdrop-filter: blur(14px);
  border: 1px solid var(--line);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
}
.brand { display: flex; align-items: center; gap: 12px; text-decoration: none; color: var(--text); }
.brand .mark { width: 40px; height: 40px; border-radius: 12px; flex: none; box-shadow: 0 8px 20px hsl(${hue} 90% 50% / 0.35); }
.brand-text { display: flex; flex-direction: column; line-height: 1.2; min-width: 0; }
.brand-text strong { font-size: 1rem; letter-spacing: -0.01em; overflow-wrap: anywhere; }
.brand-text small { color: var(--muted); font-size: 0.74rem; text-transform: uppercase; letter-spacing: 0.09em; }
.nav { display: flex; flex-direction: column; gap: 4px; }
.nav-link {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 12px;
  border-radius: var(--radius-sm);
  color: var(--muted);
  text-decoration: none;
  font-size: 0.92rem;
  font-weight: 600;
  transition: background 0.18s var(--ease), color 0.18s var(--ease), transform 0.18s var(--ease);
}
.nav-link .icon { width: 18px; height: 18px; flex: none; }
.nav-link:hover { background: rgba(255, 255, 255, 0.06); color: var(--text); transform: translateX(2px); }
.nav-link.active {
  background: linear-gradient(120deg, var(--accent), var(--accent-2));
  color: #fff;
  box-shadow: 0 10px 24px hsl(${hue} 90% 50% / 0.35);
}
.sidebar-foot {
  display: flex;
  align-items: center;
  gap: 8px;
  color: var(--muted);
  font-size: 0.76rem;
  border-top: 1px solid var(--line);
  padding-top: 14px;
}
.pulse { width: 8px; height: 8px; border-radius: 50%; background: var(--ok); box-shadow: 0 0 0 0 var(--ok); animation: pulse 2.2s infinite; }
@keyframes pulse {
  0% { box-shadow: 0 0 0 0 rgba(74, 222, 128, 0.55); }
  70% { box-shadow: 0 0 0 9px rgba(74, 222, 128, 0); }
  100% { box-shadow: 0 0 0 0 rgba(74, 222, 128, 0); }
}

/* ---- hero ---- */
.main { min-width: 0; }
.hero {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 20px;
  padding: 26px 28px;
  margin-bottom: 22px;
  border: 1px solid var(--line);
  border-radius: var(--radius);
  background:
    linear-gradient(135deg, hsl(${hue} 90% 50% / 0.16), transparent 55%),
    var(--panel);
  backdrop-filter: blur(14px);
  box-shadow: var(--shadow);
  overflow: hidden;
}
.hero-text { min-width: 0; }
.eyebrow {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 5px 12px;
  border-radius: 999px;
  background: var(--accent-soft);
  border: 1px solid hsl(${hue} 90% 66% / 0.35);
  color: var(--accent);
  font-size: 0.74rem;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}
.eyebrow .icon { width: 14px; height: 14px; }
.hero h1 {
  margin: 12px 0 6px;
  font-size: clamp(1.7rem, 3.4vw, 2.4rem);
  letter-spacing: -0.03em;
  line-height: 1.1;
  background: linear-gradient(100deg, #ffffff, hsl(${hue} 90% 82%));
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
}
.hero-art {
  flex: none;
  display: grid;
  place-items: center;
  width: 108px;
  height: 108px;
  border-radius: 26px;
  background: linear-gradient(135deg, hsl(${hue} 90% 55% / 0.35), hsl(${(hue + 60) % 360} 90% 55% / 0.15));
  border: 1px solid var(--line-strong);
}
.hero-icon { width: 52px; height: 52px; color: var(--accent); stroke-width: 1.3; }
.sub { color: var(--muted); margin: 0; font-size: 0.94rem; }
.sub.error, .msg.error { color: var(--danger); }

/* ---- cards ---- */
.cols { display: grid; grid-template-columns: minmax(0, 5fr) minmax(0, 7fr); gap: 22px; align-items: start; }
.card {
  background: var(--panel);
  backdrop-filter: blur(12px);
  border: 1px solid var(--line);
  border-radius: var(--radius);
  padding: 22px;
  margin-bottom: 22px;
  box-shadow: var(--shadow);
  transition: border-color 0.2s var(--ease), transform 0.2s var(--ease);
}
.card:hover { border-color: var(--line-strong); }
.card-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 16px; }
.card h2 { margin: 0; font-size: 1.05rem; letter-spacing: -0.01em; }
.card-icon { width: 20px; height: 20px; color: var(--accent); }
.tag {
  padding: 4px 10px;
  border-radius: 999px;
  background: rgba(74, 222, 128, 0.14);
  color: var(--ok);
  font-size: 0.7rem;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}
.count {
  min-width: 30px;
  text-align: center;
  padding: 3px 9px;
  border-radius: 999px;
  background: var(--accent-soft);
  color: var(--accent);
  font-size: 0.8rem;
  font-weight: 700;
}

/* ---- stats + chart ---- */
.stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 14px; }
.stat {
  position: relative;
  padding: 16px 16px 14px;
  border-radius: var(--radius-sm);
  border: 1px solid var(--line);
  background: linear-gradient(160deg, rgba(255, 255, 255, 0.06), rgba(255, 255, 255, 0.02));
  overflow: hidden;
}
.stat::after {
  content: '';
  position: absolute;
  inset: 0 auto 0 0;
  width: 3px;
  background: var(--accent);
}
.stat.tone-b::after { background: var(--accent-2); }
.stat.tone-c::after { background: #fbbf24; }
.stat.tone-d::after { background: var(--ok); }
.stat .stat-k { display: block; color: var(--muted); font-size: 0.76rem; text-transform: uppercase; letter-spacing: 0.07em; }
.stat .stat-v { display: block; margin-top: 6px; font-size: 1.55rem; font-weight: 800; letter-spacing: -0.03em; }
.chart {
  display: flex;
  align-items: flex-end;
  gap: 5px;
  height: 132px;
  margin-top: 20px;
  padding: 12px 12px 0;
  border-radius: var(--radius-sm);
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.04), transparent);
  border: 1px solid var(--line);
  position: relative;
}
.bar {
  flex: 1;
  min-width: 4px;
  border-radius: 6px 6px 2px 2px;
  background: linear-gradient(180deg, var(--accent), var(--accent-2));
  box-shadow: 0 6px 14px hsl(${hue} 90% 50% / 0.3);
  transition: height 0.5s var(--ease), filter 0.2s var(--ease);
}
.bar:hover { filter: brightness(1.25); }
.chart-base { position: absolute; left: 12px; right: 12px; bottom: 10px; height: 1px; background: var(--line-strong); }

/* ---- forms ---- */
label { display: block; font-size: 0.78rem; font-weight: 600; color: var(--muted); margin: 14px 0 6px; letter-spacing: 0.02em; }
input, textarea {
  width: 100%;
  padding: 11px 13px;
  border-radius: var(--radius-sm);
  border: 1px solid var(--line);
  background: rgba(6, 11, 24, 0.72);
  color: var(--text);
  font-size: 0.95rem;
  font-family: inherit;
  transition: border-color 0.18s var(--ease), box-shadow 0.18s var(--ease);
}
input::placeholder, textarea::placeholder { color: #64708f; }
input:focus, textarea:focus {
  outline: none;
  border-color: var(--accent);
  box-shadow: 0 0 0 3px hsl(${hue} 92% 66% / 0.22);
}
textarea { resize: vertical; }
button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  margin-top: 16px;
  padding: 11px 20px;
  border-radius: var(--radius-sm);
  border: 1px solid transparent;
  background: linear-gradient(120deg, var(--accent), var(--accent-2));
  color: #fff;
  font-weight: 700;
  font-size: 0.92rem;
  font-family: inherit;
  cursor: pointer;
  box-shadow: 0 10px 22px hsl(${hue} 90% 50% / 0.28);
  transition: transform 0.16s var(--ease), box-shadow 0.16s var(--ease), filter 0.16s var(--ease);
}
button:hover { transform: translateY(-1px); filter: brightness(1.06); }
button:active { transform: translateY(0); }
.btn-icon { width: 16px; height: 16px; }
button.secondary {
  background: rgba(255, 255, 255, 0.05);
  border-color: var(--line-strong);
  color: var(--text);
  box-shadow: none;
}
button.secondary:hover { background: rgba(255, 255, 255, 0.09); }
button.full { width: 100%; margin-top: 14px; }
.btn-row { display: flex; gap: 10px; flex-wrap: wrap; }
.btn-row button { flex: 1 1 140px; }

/* ---- list ---- */
.search-row { position: relative; margin-bottom: 14px; }
.search-row input { padding-left: 38px; }
.search-row button { margin-top: 0; }
.search-icon { position: absolute; left: 13px; top: 50%; transform: translateY(-50%); color: var(--muted); display: grid; place-items: center; }
.search-icon .icon { width: 17px; height: 17px; }
ul { list-style: none; margin: 0; padding: 0; }
.row-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  margin-bottom: 8px;
  border-radius: var(--radius-sm);
  border: 1px solid var(--line);
  background: rgba(255, 255, 255, 0.03);
  transition: transform 0.18s var(--ease), border-color 0.18s var(--ease), background 0.18s var(--ease);
  animation: rise 0.32s var(--ease) both;
}
.row-item:hover { transform: translateX(3px); border-color: var(--line-strong); background: rgba(255, 255, 255, 0.06); }
@keyframes rise { from { opacity: 0; transform: translateY(6px); } to { opacity: 1; transform: none; } }
.avatar {
  flex: none;
  display: grid;
  place-items: center;
  width: 36px;
  height: 36px;
  border-radius: 11px;
  background: linear-gradient(135deg, var(--accent), var(--accent-2));
  color: #fff;
  font-size: 0.8rem;
  font-weight: 800;
}
.row-body { flex: 1; min-width: 0; display: flex; flex-direction: column; }
.row-body .title { font-weight: 600; overflow-wrap: anywhere; }
.row-body .meta { color: var(--muted); font-size: 0.79rem; }
.amount { font-variant-numeric: tabular-nums; font-weight: 700; color: var(--accent); font-size: 0.9rem; }
.actions { display: flex; gap: 6px; }
button.icon-btn {
  margin: 0;
  width: 30px;
  height: 30px;
  padding: 0;
  border-radius: 9px;
  background: rgba(255, 255, 255, 0.06);
  border: 1px solid var(--line);
  color: var(--muted);
  font-size: 0.85rem;
  box-shadow: none;
}
button.icon-btn:hover { background: rgba(255, 255, 255, 0.12); color: var(--text); }
button.icon-btn.danger:hover { color: var(--danger); border-color: rgba(255, 107, 129, 0.5); }
.empty { text-align: center; padding: 34px 12px; color: var(--muted); }
.empty p { margin: 6px 0; }
.empty-icon { width: 46px; height: 46px; color: var(--accent); opacity: 0.6; }

/* ---- reports ---- */
.report .stats { margin-bottom: 18px; }
.tbl { width: 100%; border-collapse: collapse; }
.tbl th, .tbl td { text-align: left; padding: 11px 10px; border-bottom: 1px solid var(--line); font-size: 0.88rem; }
.tbl th { color: var(--muted); font-weight: 700; font-size: 0.74rem; text-transform: uppercase; letter-spacing: 0.08em; }
.tbl tbody tr { transition: background 0.16s var(--ease); }
.tbl tbody tr:hover { background: rgba(255, 255, 255, 0.04); }
.tbl tr:last-child td { border-bottom: none; }
.facts { margin-top: 14px; display: grid; gap: 10px; }
.facts li { display: flex; align-items: center; gap: 10px; color: var(--muted); font-size: 0.88rem; }
.facts .icon { width: 17px; height: 17px; color: var(--accent); flex: none; }

.muted { color: var(--muted); }
.msg { min-height: 1.2em; font-size: 0.86rem; margin-top: 10px; }
.who { color: var(--muted); font-size: 0.86rem; margin: 10px 0 0; }
.icon { width: 20px; height: 20px; }

@media (max-width: 980px) {
  .shell { grid-template-columns: 1fr; gap: 18px; padding: 18px 16px 56px; }
  .sidebar { position: static; flex-direction: row; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 14px; padding: 14px; }
  .nav { flex-direction: row; flex-wrap: wrap; }
  .sidebar-foot { display: none; }
  .cols { grid-template-columns: 1fr; }
  .hero { padding: 20px; }
  .hero-art { width: 76px; height: 76px; border-radius: 20px; }
  .hero-icon { width: 36px; height: 36px; }
}
@media (max-width: 520px) {
  .row-item { flex-wrap: wrap; }
  .amount { margin-left: 48px; }
  .card { padding: 18px; }
}
@media (prefers-reduced-motion: reduce) {
  * { animation: none !important; transition: none !important; }
}
`;
}

function wranglerJsonc({ table, realtime, backend = true }) {
  // A browser-only product ships no Worker, so it must declare no `main`: wrangler loads the
  // declared entry point before anything else and refuses to deploy a config whose main is
  // a file that was never generated. The product would have been a website nobody could host.
  return `{
  "name": "generated-${table}-api",${backend ? `
  "main": "worker/index.js",` : ''}
  "workers_dev": ${backend ? 'true' : 'false'},
  "compatibility_date": "2026-08-19",
  "compatibility_flags": ["nodejs_compat"],
  "assets": {
    "directory": "./www"${backend ? `,
    "binding": "ASSETS"` : ''}
  },
  "d1_databases": ${backend ? `[
    {
      "binding": "DB",
      "database_name": "generated_${table}",
      "database_id": "replace-with-your-d1-database-id",
      "migrations_dir": "migrations"
    }
  ]` : '[]'}${realtime ? `,
  "durable_objects": {
    "bindings": [{ "name": "LIVE", "class_name": "LiveConnections" }]
  },
  "exports": {
    "LiveConnections": { "type": "durable-object", "storage": "sqlite" }
  }` : ''}
}
`;
}

function readme({ spec, architecture, label, table }) {
  const reqs = (spec.requirements ?? []).map((r) => `- **${r.id}** — ${r.title}`).join('\n');
  return `# ${label}

Generated by MAULI 2.0 from the founder's command:

> ${String(spec.command ?? '').replace(/^/gm, '> ')}

## Architecture

${architecture.layers.map((l) => `- **${l.label}** — ${l.rationale}`).join('\n')}

## Run it

\`\`\`bash
npm install
npx wrangler d1 create generated_${table}     # copy the id into wrangler.jsonc
npx wrangler d1 migrations apply generated_${table} --local
npx wrangler dev                               # serves the frontend AND the Worker API
\`\`\`

The frontend (\`www/\`) is bound as the Worker's static assets and the Worker
(\`worker/index.js\`) serves the API, so one deploy is the whole product. The pages call
\`/api/${table}s\` for every read and write, so there is no second copy of the data in the
browser. The table name is quoted in every statement — \`${table}\` is your own noun, and it
may be a SQL keyword.

## Pages

Every page is a real file and every page links to the others through the top navigation:

- \`www/index.html\` — Dashboard: account, overview cards, a 14-day activity chart, add an entry, and the full ${table} list
- \`www/reports.html\` — Reports: totals, activity and the latest ${table}s
- \`www/settings.html\` — Settings: account controls, a JSON export of your data, and what the product is built on

## The look

The UI is a designed product surface, not a wireframe: a sticky sidebar with icon
navigation, a gradient hero, colour-coded stat cards, an empty state with artwork, and
row hover states. Every icon is inline SVG and the chart is drawn from the stored rows,
so the pages render identically offline — there is no image, font or chart library to
fetch and nothing that can 404. The accent hue is derived from the product name, so two
products do not ship the same purple.

## Requirements this build implements

${reqs}
`;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/**
 * Generate the full product the specification asked for.
 * @returns {{files:Array<{path:string,content:string}>, summary:string, table:string,
 *   label:string, architecture:object}}
 */
export function generateFullStackApp(spec, architecture, { objective = '' } = {}) {
  const table = domainEntity(spec);
  const entity = camel(table);
  const label = entityLabel(spec);
  // A browser-only product keeps its records on the device, so the only place its domain
  // can be named is the app itself. The catalogue's generic entity ("entry") gave a founder
  // a medicine tracker whose every identifier said "entry" — the product never said what it
  // was for. The founder's own noun is used instead whenever there is one.
  const localNoun = architecture.backend
    ? null
    : (spec.inferredFromDomain ?? (spec.domainWords ?? []).find((w) => typeof w === 'string' && w.length > 3) ?? null);
  const frontTable = localNoun ?? table;
  const frontEntity = camel(frontTable);
  const frontLabel = localNoun ? frontEntity : label;
  // A browser-only architecture ships no server. Emitting a Worker and a D1 migration for a
  // product that promised to keep its records on the device gave the founder a product whose
  // own documentation contradicted its own code.
  const files = [
    { path: 'www/index.html', content: frontendHtml({ spec, architecture, table: frontTable, entity: frontEntity, label: frontLabel, page: 'dashboard' }) },
    { path: 'www/reports.html', content: frontendHtml({ spec, architecture, table: frontTable, entity: frontEntity, label: frontLabel, page: 'reports' }) },
    { path: 'www/settings.html', content: frontendHtml({ spec, architecture, table: frontTable, entity: frontEntity, label: frontLabel, page: 'settings' }) },
    { path: 'www/app.js', content: frontendJs({ spec, architecture, table: frontTable, entity: frontEntity, label: frontLabel }) },
    { path: 'www/styles.css', content: frontendCss({ label: frontLabel, hue: accentFor(frontLabel) }) },
    ...(architecture.backend
      ? [
        { path: 'worker/index.js', content: workerSource({ spec, architecture, table, entity, label }) },
        { path: 'migrations/0001_init.sql', content: schemaSql({ table, auth: architecture.auth, realtime: architecture.realtime, due: wantsScheduling(spec) }) },
        { path: 'wrangler.jsonc', content: wranglerJsonc({ table, realtime: architecture.realtime }) }
      ]
      : [{ path: 'wrangler.jsonc', content: wranglerJsonc({ table: frontTable, realtime: false, backend: false }) }]),
    {
      path: 'package.json',
      content: JSON.stringify({
        name: `generated-${table}`,
        version: '1.0.0',
        private: true,
        type: 'module',
        scripts: {
          dev: 'wrangler dev',
          deploy: 'wrangler deploy',
          'db:migrate:local': `wrangler d1 migrations apply generated_${table} --local`,
          test: 'node --test'
        }
      }, null, 2)
    },
    { path: 'README.md', content: readme({ spec, architecture, label, table }) }
  ];
  return {
    files,
    table,
    api: `/api/${plural(table)}`,
    label,
    architecture,
    summary: `${label} — ${architecture.label}. ${architecture.backend ? 'Worker API over D1' : 'local device store'}${architecture.auth ? ', session-protected' : ''}${architecture.realtime ? ', live updates over WebSocket' : ''}.`,
    tests: [
      'Create a record through the UI and see it in the list',
      'Reload the page and confirm the record is still there',
      ...(architecture.auth ? ['Register, log out, and confirm a protected read is refused while signed out'] : []),
      ...(architecture.realtime ? ['Open two tabs, add a record in one, and see it appear in the other'] : [])
    ],
    notes: [`Generated from ${spec.requirements?.length ?? 0} extracted requirements via ${spec.productType ?? 'generic'} specification.`]
  };
}

export default generateFullStackApp;
