import { ok, fail, json, now } from './core.js';
import { store } from './store.js';
import { seedAgents, listAgents } from './agents.js';
import { listProjects } from './projects.js';
import { listTasks } from './tasks.js';
import { listApprovals, decideApproval } from './governance.js';
import { planCommand, resumeApprovedCommand } from './orchestrator.js';
import { listTools, ensureBuiltinTools } from './tools.js';
import { getArtifact, listProjectArtifacts, listTaskArtifacts } from './artifacts.js';
import { collectProjectFiles, createZip } from './zip.js';
import { ensureSchema, hasD1, d1List, d1Events } from './db.js';
import { recoverRunningExecutions } from './execution.js';
import { requireFounder, checkRateLimit } from './auth.js';
import { runL1SelfTest } from './self-test.js';
import { diagnoseResultPersistence, saveCommandResult } from './result-recorder.js';

const dashboard = () => `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MAULI 2.0 Command Center</title><style>body{margin:0;font-family:system-ui;background:#080d18;color:#eef2ff}main{padding:20px;max-width:1000px;margin:auto}.card{background:#111a30;border:1px solid #29355c;border-radius:14px;padding:16px;margin-bottom:14px}button{padding:10px 14px;border:0;border-radius:8px;cursor:pointer;margin:4px 4px 4px 0}textarea{width:100%;min-height:90px;box-sizing:border-box;background:#080d18;color:#fff;border:1px solid #33406a;padding:10px;border-radius:8px}.result{white-space:pre-wrap;word-break:break-word;line-height:1.45}.muted{opacity:.7}.download{display:inline-block;margin-top:12px;padding:10px 14px;border-radius:8px;background:#eef2ff;color:#080d18;text-decoration:none;font-weight:700;cursor:pointer}.diag{margin-top:10px;padding:10px;border:1px solid #33406a;border-radius:8px}</style></head><body><main><div class="card"><h1>MAULI 2.0</h1><p>Autonomous AI Company — L1 Command Center</p><textarea id="cmd" placeholder="Founder command"></textarea><br><button id="sendBtn" type="button">Send to MAULI</button><button id="testBtn" type="button">Run L1 Self-Test</button><button id="diagBtn" type="button">Check Result Writer</button><div id="diag" class="diag muted"></div></div><div class="card"><h2>Latest Project</h2><div id="state" class="result muted">Loading...</div><div id="download"></div></div></main><script>
(() => {
 const $=id=>document.getElementById(id),state=$("state"),download=$("download"),diagOut=$("diag");
 const setState=v=>{state.textContent=typeof v==='string'?v:JSON.stringify(v,null,2)};
 async function key(){return window.prompt("Founder API key")||""}
 async function send(){try{const command=$("cmd").value.trim();if(!command){setState("Enter a Founder command first.");return}const k=await key();if(!k)return;setState("Executing command...");const r=await fetch("/api/command",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+k},body:JSON.stringify({command})}),j=await r.json();setState(j.data?.result||j);await load()}catch(e){setState({error:e?.message||String(e)})}}
 async function test(){try{const k=await key();if(!k)return;setState("Running self-test...");const r=await fetch("/api/self-test",{headers:{authorization:"Bearer "+k}}),j=await r.json();setState(j.data?.result||j)}catch(e){setState({error:e?.message||String(e)})}}
 async function diag(){diagOut.textContent="Checking Result Writer...";try{const k=await key();if(!k){diagOut.textContent="Cancelled: Founder API key required.";return}const r=await fetch("/api/result-diagnostic",{headers:{authorization:"Bearer "+k},cache:"no-store"}),j=await r.json();diagOut.textContent=JSON.stringify(j.data?.result||j,null,2)}catch(e){diagOut.textContent=JSON.stringify({error:e?.message||String(e)},null,2)}}
 async function downloadZip(path){try{const k=await key();if(!k||!path)return;const r=await fetch(path,{headers:{authorization:"Bearer "+k}});if(!r.ok){alert("ZIP download failed: "+r.status);return}const blob=await r.blob(),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="mauli-project.zip";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){alert("ZIP download failed: "+(e?.message||String(e)))}}
 function latest(d){const projects=Array.isArray(d.projects)?d.projects.slice():[];projects.sort((a,b)=>new Date(b.updatedAt||b.createdAt||0)-new Date(a.updatedAt||a.createdAt||0));const p=projects[0]||null;const tasks=p&&Array.isArray(d.tasks)?d.tasks.filter(x=>x.projectId===p.id):[];return{project:p,tasks}}
 async function load(){try{const r=await fetch("/api/state",{cache:"no-store"}),j=await r.json();if(!r.ok||!j.ok){setState(j);download.innerHTML="";return}const x=latest(j.data||{});setState({project:x.project?{id:x.project.id,name:x.project.name,objective:x.project.objective,status:x.project.state,requirements:x.project.requirements||[]}:null,tasks:x.tasks.map(t=>({title:t.title,state:t.state,executor:t.executor,agentId:t.assignedAgentId||t.agentId||null}))});const artifacts=(j.data?.artifacts||[]).filter(a=>a.projectId===x.project?.id&&a.type==="final-delivery").sort((a,b)=>new Date(b.updatedAt||b.createdAt||0)-new Date(a.updatedAt||a.createdAt||0));const path=artifacts[0]?.metadata?.downloadPath;download.innerHTML="";if(path&&x.project?.state==="completed"){const b=document.createElement("button");b.className="download";b.type="button";b.textContent="Download ZIP";b.addEventListener("click",()=>downloadZip(path));download.appendChild(b)}}catch(e){setState({error:"Dashboard state load failed",message:e?.message||String(e)})}}
 $("sendBtn").addEventListener("click",send);$("testBtn").addEventListener("click",test);$("diagBtn").addEventListener("click",diag);load();setInterval(load,5000)
})();</script></body></html>`;
function artifactJson(a){return a?ok({artifact:a}):fail('Artifact not found',404)}
function isIsolatedTestEnv(env){return env?.SKIP_RESULT_PERSISTENCE===true||env?.SKIP_RESULT_PERSISTENCE==='true'||env?.MAULI_TEST_MODE===true||env?.MAULI_TEST_MODE==='true'}
function completionSafe(project,tasks){if(!project||project.state!=='completed')return true;return tasks.filter(t=>t.projectId===project.id).every(t=>t.state==='completed'||t.state==='failed')&&tasks.filter(t=>t.projectId===project.id).every(t=>t.state!=='queued'&&t.state!=='working')}
export default {async fetch(request,env){try{await ensureSchema(env);store.configure(env);if(!store.hydrated)await store.hydrate();ensureBuiltinTools();seedAgents();const recoveredRuns=recoverRunningExecutions();const url=new URL(request.url);
 if(request.method==='GET'&&url.pathname==='/')return new Response(dashboard(),{headers:{'content-type':'text/html;charset=UTF-8','cache-control':'no-store'}});
 if(request.method==='GET'&&url.pathname==='/api/health')return ok({service:'mauli2.0',status:'healthy',persistence:hasD1(env),hydrated:store.hydrated,ai:Boolean(env?.AI),recoveredRuns:recoveredRuns.length,time:now()});
 if(request.method==='GET'&&url.pathname==='/api/state'){const [agents,projects,tasks,approvals,events]=hasD1(env)?await Promise.all([d1List(env,'agents'),d1List(env,'projects'),d1List(env,'tasks'),d1List(env,'approvals'),d1Events(env)]):[listAgents(),listProjects(),listTasks(),listApprovals(),store.recentEvents()];const safeProjects=projects.map(p=>{const pt=tasks.filter(t=>t.projectId===p.id);return p.state==='completed'&&!completionSafe(p,pt)?{...p,state:'active',completionGuard:'blocked-until-all-tasks-finish'}:p});return ok({agents,projects:safeProjects,tasks,approvals,tools:listTools(),artifacts:store.list('artifacts'),events,recoveredRuns})}
 if(request.method==='GET'&&url.pathname==='/api/self-test'){const limit=checkRateLimit(request);if(!limit.ok)return fail(limit.error,limit.status,{retryAfter:limit.retryAfter});const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);const result=runL1SelfTest();store.addEvent('self_test.completed',{score:result.score,status:result.status});return ok({result})}
 if(request.method==='GET'&&url.pathname==='/api/result-diagnostic'){const limit=checkRateLimit(request);if(!limit.ok)return fail(limit.error,limit.status,{retryAfter:limit.retryAfter});const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);const result=await diagnoseResultPersistence(env);store.addEvent('result_persistence.diagnostic',{ok:result.ok,tokenConfigured:result.tokenConfigured,reason:result.reason||null});return ok({result})}
 if(request.method==='GET'&&url.pathname==='/api/artifacts'){const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);const projectId=url.searchParams.get('projectId'),taskId=url.searchParams.get('taskId');return ok({artifacts:projectId?listProjectArtifacts(projectId):taskId?listTaskArtifacts(taskId):store.list('artifacts')})}
 if(request.method==='GET'&&url.pathname.startsWith('/api/artifacts/')&&url.pathname.endsWith('/download')){const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);const parts=url.pathname.split('/'),artifactId=parts[parts.length-2],artifact=getArtifact(artifactId);if(!artifact)return fail('Artifact not found',404);const files=collectProjectFiles(artifact.projectId,artifact,store);if(!files.length)return fail('No downloadable project files found',404);const zip=createZip(files),safeName=String(artifact.projectId).replace(/[^a-zA-Z0-9_-]/g,'_');return new Response(zip,{status:200,headers:{'content-type':'application/zip','content-disposition':`attachment; filename="mauli-${safeName}.zip"`,'cache-control':'no-store'}})}
 if(request.method==='GET'&&url.pathname.startsWith('/api/artifacts/')){const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);return artifactJson(getArtifact(url.pathname.split('/').pop()))}
 if(request.method==='POST'&&url.pathname==='/api/command'){const limit=checkRateLimit(request);if(!limit.ok)return fail(limit.error,limit.status,{retryAfter:limit.retryAfter});const body=await json(request);if(!body.command)return fail('Founder command is required',400);const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);const isolatedTest=isIsolatedTestEnv(env),result=await planCommand(body.command,env);const projects=result?.project? [result.project] : listProjects();const tasks=listTasks();const p=projects.find(x=>x?.id===result?.project?.id)||result?.project;const pt=p?tasks.filter(t=>t.projectId===p.id):[];if(p?.state==='completed'&&!completionSafe(p,pt))result.project={...p,state:'active',completionGuard:'blocked-until-all-tasks-finish'};const persistedPayload={command:body.command,generatedAt:now(),result};const saved=isolatedTest?{saved:true,skipped:true,testMode:true,reason:'Result persistence disabled for isolated test'}:await saveCommandResult(persistedPayload,env);if(!saved.saved)return fail('Command executed but Result file persistence failed',502,{resultFile:saved,result});return ok({result,resultFile:saved},201)}
 if(request.method==='POST'&&url.pathname.startsWith('/api/approvals/')){const limit=checkRateLimit(request);if(!limit.ok)return fail(limit.error,limit.status,{retryAfter:limit.retryAfter});const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);const approvalId=url.pathname.split('/').pop(),body=await json(request),result=decideApproval(approvalId,Boolean(body.approved),body.note??'');if(!result)return fail('Approval not found',404);if(result.state==='rejected')return ok({approval:result,status:'rejected'});return ok({approval:result,result:await resumeApprovedCommand(approvalId,env)})}
 return fail('Route not found',404)}catch(error){return fail(error.message||'Internal error',500)}}};
