import { ok, fail, json, now } from './core.js';
import { store } from './store.js';
import { seedAgents, listAgents } from './agents.js';
import { listProjects } from './projects.js';
import { listTasks } from './tasks.js';
import { listApprovals, decideApproval } from './governance.js';
import { planCommand, resumeApprovedCommand } from './orchestrator.js';
import { listTools, ensureBuiltinTools } from './tools.js';
import { getArtifact, listProjectArtifacts, listTaskArtifacts } from './artifacts.js';
import { ensureSchema, hasD1, d1List, d1Events } from './db.js';
import { recoverRunningExecutions } from './execution.js';
import { requireFounder, checkRateLimit } from './auth.js';
import { runL1SelfTest } from './self-test.js';
import { diagnoseResultPersistence, saveCommandResult } from './result-recorder.js';

const dashboard = () => '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MAULI 2.0 Command Center</title><style>body{margin:0;font-family:system-ui;background:#080d18;color:#eef2ff}main{padding:24px;max-width:1200px;margin:auto}.card{background:#111a30;border:1px solid #29355c;border-radius:14px;padding:18px;margin-bottom:16px}button{padding:10px 14px;border:0;border-radius:8px;cursor:pointer}textarea{width:100%;min-height:110px;box-sizing:border-box;background:#080d18;color:#fff;border:1px solid #33406a;padding:10px;border-radius:8px}.result{white-space:pre-wrap;word-break:break-word}</style></head><body><main><div class="card"><h1>MAULI 2.0</h1><p>Autonomous AI Company — L1 Command Center</p><textarea id="cmd" placeholder="Founder command"></textarea><br><br><button onclick="send()">Send to MAULI</button> <button onclick="test()">Run L1 Self-Test</button> <button onclick="diag()">Check Result Writer</button><pre id="out" class="result"></pre></div><div class="card"><h2>Live State</h2><pre id="state" class="result"></pre></div></main><script>async function key(){return prompt("Founder API key")||""}async function send(){const command=document.getElementById("cmd").value.trim();if(!command)return;const k=await key();if(!k)return;const r=await fetch("/api/command",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+k},body:JSON.stringify({command})});document.getElementById("out").textContent=JSON.stringify(await r.json(),null,2);load()}async function test(){const k=await key();if(!k)return;const r=await fetch("/api/self-test",{headers:{authorization:"Bearer "+k}});document.getElementById("out").textContent=JSON.stringify(await r.json(),null,2)}async function diag(){const k=await key();if(!k)return;const r=await fetch("/api/result-diagnostic",{headers:{authorization:"Bearer "+k}});document.getElementById("out").textContent=JSON.stringify(await r.json(),null,2)}async function load(){const r=await fetch("/api/state");document.getElementById("state").textContent=JSON.stringify(await r.json(),null,2)}load();setInterval(load,5000)</script></body></html>';

function artifactJson(artifact) { return artifact ? ok({ artifact }) : fail('Artifact not found',404); }

export default { async fetch(request, env) { try {
  await ensureSchema(env); store.configure(env); if(!store.hydrated) await store.hydrate(); ensureBuiltinTools(); seedAgents(); const recoveredRuns=recoverRunningExecutions(); const url=new URL(request.url);
  if(request.method==='GET'&&url.pathname==='/') return new Response(dashboard(),{headers:{'content-type':'text/html;charset=UTF-8'}});
  if(request.method==='GET'&&url.pathname==='/api/health') return ok({service:'mauli2.0',status:'healthy',persistence:hasD1(env),hydrated:store.hydrated,ai:Boolean(env?.AI),recoveredRuns:recoveredRuns.length,time:now()});
  if(request.method==='GET'&&url.pathname==='/api/state'){const [agents,projects,tasks,approvals,events]=hasD1(env)?await Promise.all([d1List(env,'agents'),d1List(env,'projects'),d1List(env,'tasks'),d1List(env,'approvals'),d1Events(env)]):[listAgents(),listProjects(),listTasks(),listApprovals(),store.recentEvents()];return ok({agents,projects,tasks,approvals,tools:listTools(),artifacts:store.list('artifacts'),events,recoveredRuns});}
  if(request.method==='GET'&&url.pathname==='/api/self-test'){const limit=checkRateLimit(request);if(!limit.ok)return fail(limit.error,limit.status,{retryAfter:limit.retryAfter});const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);const result=runL1SelfTest();store.addEvent('self_test.completed',{score:result.score,status:result.status});return ok({result});}
  if(request.method==='GET'&&url.pathname==='/api/result-diagnostic'){const limit=checkRateLimit(request);if(!limit.ok)return fail(limit.error,limit.status,{retryAfter:limit.retryAfter});const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);const result=await diagnoseResultPersistence(env);store.addEvent('result_persistence.diagnostic',{ok:result.ok,tokenConfigured:result.tokenConfigured,reason:result.reason||null});return ok({result});}
  if(request.method==='GET'&&url.pathname==='/api/artifacts'){const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);const projectId=url.searchParams.get('projectId');const taskId=url.searchParams.get('taskId');const artifacts=projectId?listProjectArtifacts(projectId):taskId?listTaskArtifacts(taskId):store.list('artifacts');return ok({artifacts});}
  if(request.method==='GET'&&url.pathname.startsWith('/api/artifacts/')){const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);return artifactJson(getArtifact(url.pathname.split('/').pop()));}
  if(request.method==='POST'&&url.pathname==='/api/command'){const limit=checkRateLimit(request);if(!limit.ok)return fail(limit.error,limit.status,{retryAfter:limit.retryAfter});const body=await json(request);if(!body.command)return fail('Founder command is required',400);const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);const result=await planCommand(body.command,env);const saved=env?.SKIP_RESULT_PERSISTENCE ? {saved:true,skipped:true,reason:'Result persistence disabled for isolated test'} : await saveCommandResult({ok:true,data:{result}},env);if(!saved.saved)return fail('Command executed but Result file persistence failed',502,{resultFile:saved,result});return ok({result,resultFile:saved},201);}
  if(request.method==='POST'&&url.pathname.startsWith('/api/approvals/')){const limit=checkRateLimit(request);if(!limit.ok)return fail(limit.error,limit.status,{retryAfter:limit.retryAfter});const auth=requireFounder(request,env);if(!auth.ok)return fail(auth.error,auth.status);const approvalId=url.pathname.split('/').pop();const body=await json(request);const result=decideApproval(approvalId,Boolean(body.approved),body.note??'');if(!result)return fail('Approval not found',404);if(result.state==='rejected')return ok({approval:result,status:'rejected'});return ok({approval:result,result:await resumeApprovedCommand(approvalId,env)});}
  return fail('Route not found',404);
} catch(error){return fail(error.message||'Internal error',500);} } };