import { modelRegistry } from './model-registry.js';
const COMPLEXITY_WEIGHTS={simple:{quality:.2,speed:.35,cost:.3,reasoning:.15},medium:{quality:.3,speed:.2,cost:.2,reasoning:.3},complex:{quality:.3,speed:.1,cost:.1,reasoning:.5},critical:{quality:.35,speed:.05,cost:.05,reasoning:.55}};
const CAPABILITY_ALIASES={coding:['backend','frontend','javascript'],code:['backend','frontend','javascript']};
function clamp(n,min=0,max=100){return Math.max(min,Math.min(max,n));}
export function classifyComplexity(task={}){const explicit=String(task.complexity??'').toLowerCase();if(['simple','medium','complex','critical'].includes(explicit))return explicit;const caps=task.requiredCapabilities??[];const text=String(task.description??task.objective??'');if(/critical|production|security|migration/i.test(text))return'critical';if(caps.length>=4||/architecture|e-commerce|ecommerce|platform/i.test(text))return'complex';if(caps.length>=2)return'medium';return'simple';}
function expandedCapabilities(required=[]){const set=new Set(required);for(const cap of required)for(const alias of CAPABILITY_ALIASES[String(cap).toLowerCase()]??[])set.add(alias);return[...set];}
export function scoreModel(model,{complexity='medium',estimatedContext=0,riskLevel='normal',avoidModels=[]}={}){if(avoidModels.includes(model.id)||Number(model.contextWindow??0)<Number(estimatedContext))return-Infinity;if(riskLevel==='critical'&&model.riskLevel==='restricted')return-Infinity;const w=COMPLEXITY_WEIGHTS[complexity]??COMPLEXITY_WEIGHTS.medium;const quality=Number(model.qualityScore??0),speed=Number(model.speedScore??0),cost=Number(model.costScore??0),reasoning=Number(model.reasoningScore??0),reliability=Number(model.reliabilityScore??0);const contextFit=estimatedContext?clamp(100-(estimatedContext/Math.max(1,Number(model.contextWindow))*100)):100;return quality*w.quality+speed*w.speed+cost*w.cost+reasoning*w.reasoning+reliability*.1+contextFit*.1;}
export function routeModel(task={},options={}){const required=expandedCapabilities(task.requiredCapabilities??[]);const complexity=classifyComplexity(task);const riskLevel=task.riskLevel??(complexity==='critical'?'critical':'normal');const estimatedContext=Number(task.estimatedContext??task.contextTokens??0);let candidates=modelRegistry.candidates(required,{provider:options.provider,minContextWindow:estimatedContext,riskLevel});if(!candidates.length&&required.length)candidates=modelRegistry.candidates([],{provider:options.provider,minContextWindow:estimatedContext,riskLevel});const scored=candidates.map(model=>({model,score:scoreModel(model,{complexity,estimatedContext,riskLevel,avoidModels:options.avoidModels??[]})})).filter(x=>Number.isFinite(x.score)).sort((a,b)=>b.score-a.score||a.model.id.localeCompare(b.model.id));return{selected:scored[0]?.model??null,fallback:scored[1]?.model??null,complexity,riskLevel,candidates:scored.map(x=>({modelId:x.model.id,provider:x.model.provider,score:Number(x.score.toFixed(4))})),reason:scored.length?'best-fit capability/quality/speed/cost/reliability score':'no eligible model'};}
export function routeForRetry(task,previousModelId){return routeModel(task,{avoidModels:previousModelId?[previousModelId]:[]});}
