import { id, now } from './core.js';
import { store } from './store.js';
import { createProject, addTaskToProject } from './projects.js';
import { seedAgents, selectAgents, updateAgent, recordAgentOutcome } from './agents.js';
import { recordAgentTaskLearning } from './agent-learning.js';
import { riskLevel, requiresApproval, requestApproval, isApprovalGranted } from './governance.js';
import { remember } from './memory.js';
import { interpretWithAI } from './ai.js';
import { executeTask } from './execution.js';
import { verifyResult, retryDecision } from './verification.js';

export function interpretCommand(command) {
  const text = String(command ?? '').trim(); if (!text) throw new Error('Founder command is required');
  const capabilities = [];
  if (/(e-commerce|ecommerce|website|web|app|application|software|platform)/i.test(text)) capabilities.push('requirements');
  if (/(research|analysis|study)/i.test(text)) capabilities.push('research');
  return { id:id('intent'), command:text, objective:text, capabilities };
}
function dependenciesComplete(task) { return (task.dependsOn ?? []).every(depId => store.get('tasks', depId)?.state === 'completed'); }
function taskSpecFromPlan(plan, fallbackObjective) {
  const requirements = Array.isArray(plan?.requirements) ? plan.requirements : []; const caps = Array.isArray(plan?.capabilities) ? plan.capabilities : [];
  const map=[{key:'research',title:'Research and validate requirements',caps:['research','analysis']},{key:'product-planning',title:'Define product and architecture plan',caps:['product-planning','planning']},{key:'frontend',title:'Design frontend and user experience',caps:['frontend','ui']},{key:'backend',title:'Design backend and API implementation',caps:['backend','api']},{key:'database',title:'Design database and persistence',caps:['database','schema','sql']},{key:'security',title:'Perform security review',caps:['security','audit']},{key:'testing',title:'Create verification and QA plan',caps:['testing','verification']}];
  const selected=map.filter(x=>caps.includes(x.key)||x.caps.some(c=>caps.includes(c))); const specs=selected.length?selected:[{key:'planning',title:'Analyze requirements and produce execution plan',caps:['planning']}];
  return specs.map((s,i)=>({...s,title:requirements[i]?`${s.title}: ${requirements[i]}`:s.title,description:fallbackObjective,requiredCapabilities:s.caps,maxAttempts:3,executor:'internal.plan',sequence:i}));
}
function createPlannedTasks(project, aiPlan, objective, risk) {
  const specs=taskSpecFromPlan(aiPlan,objective),created=[];
  for(const spec of specs){const selected=selectAgents(spec.requiredCapabilities)[0]??selectAgents(['planning'])[0];const previous=created.at(-1)?.task;const task=addTaskToProject(project.id,{title:spec.title,description:spec.description,requiredCapabilities:spec.requiredCapabilities,risk,acceptance:aiPlan?.acceptanceCriteria?.length?aiPlan.acceptanceCriteria:['Clear requirements','Execution plan','Verification'],assignedAgentId:selected?.id??null,maxAttempts:spec.maxAttempts,executor:spec.executor,sequence:spec.sequence,dependsOn:previous?[previous.id]:[]});if(task)created.push({task,selectedAgent:selected});}
  return created;
}
export async function planCommand(command,env={}){seedAgents();const basic=interpretCommand(command);let aiPlan=null;if(env?.AI?.run){try{aiPlan=await interpretWithAI(env,command);}catch{aiPlan=null;}}const objective=aiPlan?.objective??basic.objective;const capabilities=[...new Set([...(basic.capabilities??[]),...(aiPlan?.capabilities??[])])];const project=createProject({name:`Project: ${objective.slice(0,60)}`,objective,founderCommand:basic.command,requirements:aiPlan?.requirements??[]});const risk=riskLevel({codeWrite:/code|build|create|develop|platform|app|website/i.test(command)});const approval=requiresApproval(risk)?requestApproval({action:`Execute founder command: ${command}`,risk,projectId:project.id}):null;const tasks=createPlannedTasks(project,{...(aiPlan??{}),capabilities},objective,risk);remember({type:'project_requirement',content:objective,scope:'project',scopeId:project.id,importance:'high',source:'founder-command'});if(approval)return{intent:basic,aiPlan,project,tasks,status:'awaiting_approval',approval};return executePlannedProject({project,task:tasks[0]?.task,selectedAgent:tasks[0]?.selectedAgent,env,plannedTasks:tasks});}
export async function executePlannedProject({project,task,selectedAgent,env={},approved=false,plannedTasks=null}){if(!task)return{project,status:'error',error:'No executable task was created'};if(!dependenciesComplete(task))return{project,firstTask:task,selectedAgent,status:'blocked',reason:'dependencies_incomplete'};if(requiresApproval(task.risk)&&!approved)return{project,firstTask:task,selectedAgent,status:'awaiting_approval'};if(selectedAgent)updateAgent(selectedAgent.id,{state:'working',currentTaskId:task.id,heartbeatAt:now()});const working=store.put('tasks',{...task,state:'working',startedAt:now(),attempts:(task.attempts??0)+1,id:task.id});let execution=await executeTask(working,{env,approved,agentId:selectedAgent?.id??null});let verification=verifyResult(working,execution);let attempt=1;while(!verification.passed&&attempt<(working.maxAttempts??3)){const decision=retryDecision(working,verification,attempt);if(decision.action!=='retry')break;attempt=decision.attempt;execution=await executeTask(working,{env,retry:true,attempt,approved,agentId:selectedAgent?.id??null});verification=verifyResult(working,execution);}const success=verification.passed;if(selectedAgent){recordAgentOutcome(selectedAgent.id,{success,taskId:working.id,verificationId:verification.id});recordAgentTaskLearning({agentId:selectedAgent.id,task:working,success,verification});}const status=success?'completed':'escalated';const finalTask=store.put('tasks',{...working,state:success?'completed':'failed',result:execution?.result??null,verificationId:verification.id,completedAt:success?now():undefined,id:working.id});if(selectedAgent)updateAgent(selectedAgent.id,{state:success?'available':'escalated',currentTaskId:null,heartbeatAt:now()});if(success){const next=(plannedTasks??[]).find(x=>x.task.id!==finalTask.id&&x.task.state!=='completed'&&dependenciesComplete(x.task));if(next)return executePlannedProject({project,task:next.task,selectedAgent:next.selectedAgent,env,approved,plannedTasks});}const allDone=(plannedTasks??[]).length?(plannedTasks??[]).every(x=>store.get('tasks',x.task.id)?.state==='completed'):success;const projectState=allDone?'completed':status==='escalated'?'escalated':'active';const finalProject=store.put('projects',{...project,state:projectState,id:project.id});store.addEvent('command.completed',{projectId:project.id,taskId:finalTask.id,status:projectState});return{project:finalProject,firstTask:finalTask,selectedAgent,execution,verification,status:projectState};}
export async function resumeApprovedCommand(approvalId,env={}){const approval=store.get('approvals',approvalId);if(!approval||!isApprovalGranted(approvalId))return{status:'awaiting_approval',approval};const project=store.get('projects',approval.projectId);const tasks=store.list('tasks').filter(t=>t.projectId===approval.projectId);const pending=tasks.filter(t=>t.state!=='completed');const task=pending.sort((a,b)=>(a.sequence??0)-(b.sequence??0))[0];const selectedAgent=task?.assignedAgentId?store.get('agents',task.assignedAgentId):selectAgents(task?.requiredCapabilities??['planning'])[0];if(!project||!task)return{status:'error',error:'Approved project/task not found'};return executePlannedProject({project,task,selectedAgent,env,approved:true,plannedTasks:tasks.map(t=>({task:t,selectedAgent:t.assignedAgentId?store.get('agents',t.assignedAgentId):null}))});}
