import { id, now } from './core.js';
import { store } from './store.js';
import { createProject, addTaskToProject } from './projects.js';
import { seedAgents, selectAgents, updateAgent, recordAgentOutcome } from './agents.js';
import { recordAgentTaskLearning } from './agent-learning.js';
import { riskLevel, requiresApproval, requestApproval, isApprovalGranted } from './governance.js';
import { remember } from './memory.js';
import { interpretWithAI } from './ai.js';
import { executeTask } from './execution.js';
import { verifyResult, retryDecision } from './verification.js';

export function interpretCommand(command) { const text=String(command??'').trim(); if(!text)throw new Error('Founder command is required'); const capabilities=[]; if(/(e-commerce|ecommerce|website|web|app|application|software|platform)/i.test(text))capabilities.push('requirements'); if(/(research|analysis|study)/i.test(text))capabilities.push('research'); return{id:id('intent'),command:text,objective:text,capabilities}; }
function dependenciesComplete(task){return(task.dependsOn??[]).every(depId=>store.get('tasks',depId)?.state==='completed');}
function executorForCapabilities(key,caps=[]){const c=new Set(caps);if(['frontend','ui','backend','api','database','schema','sql','security'].includes(key))return'internal.code';if(c.has('frontend')||c.has('ui')||c.has('backend')||c.has('api')||c.has('database')||c.has('schema')||c.has('sql')||c.has('security'))return'internal.code';return'internal.plan';}
const TASK_ORDER={research:10,'product-planning':20,backend:30,database:40,frontend:50,security:60,testing:70};
function taskSpecFromPlan(plan,fallbackObjective){const requirements=Array.isArray(plan?.requirements)?plan.requirements:[];const caps=Array.isArray(plan?.capabilities)?plan.capabilities:[];const map=[{key:'research',title:'Research and validate requirements',caps:['research','analysis']},{key:'product-planning',title:'Define product and architecture plan',caps:['product-planning','planning']},{key:'frontend',title:'Design frontend and user experience',caps:['frontend','ui']},{key:'backend',title:'Design backend and API implementation',caps:['backend','api']},{key:'database',title:'Design database and persistence',caps:['database','schema','sql']},{key:'security',title:'Perform security review',caps:['security','audit']},{key:'testing',title:'Create verification and QA plan',caps:['testing','verification']}];const selected=map.filter(x=>caps.includes(x.key)||x.caps.some(c=>caps.includes(c)));const specs=selected.length?selected:[{key:'planning',title:'Analyze requirements and produce execution plan',caps:['planning']}];return specs.map((s,i)=>({...s,title:requirements[i]?`${s.title}: ${requirements[i]}`:s.title,description:fallbackObjective,requiredCapabilities:s.caps,maxAttempts:3,executor:executorForCapabilities(s.key,s.caps),sequence:TASK_ORDER[s.key]??(100+i)})).sort((a,b)=>a.sequence-b.sequence);}
function createPlannedTasks(project,aiPlan,objective,risk){const specs=taskSpecFromPlan(aiPlan,objective),created=[];for(const spec of specs){const candidates=selectAgents(spec.requiredCapabilities);const selected=candidates[0]??selectAgents(['planning'])[0];const previous=created.at(-1)?.task;const task=addTaskToProject(project.id,{title:spec.title,description:spec.description,requiredCapabilities:spec.requiredCapabilities,risk,acceptance:aiPlan?.acceptanceCriteria?.length?aiPlan.acceptanceCriteria:['Clear requirements','Execution plan','Verification'],assignedAgentId:selected?.id??null,maxAttempts:spec.maxAttempts,executor:spec.executor,sequence:spec.sequence,dependsOn:previous?[previous.id]:[]});if(task)created.push({task,selectedAgent:selected});}return created;}
function taskEntries(tasks=[]){return tasks.map(entry=>{const task=store.get('tasks',entry.task?.id??entry.id)??entry.task??entry;const assignedAgentId=task?.assignedAgentId??task?.agentId??entry.selectedAgent?.id??null;return{task:assignedAgentId&&task&&!task.assignedAgentId?{...task,assignedAgentId}:task,selectedAgent:assignedAgentId?store.get('agents',assignedAgentId):entry.selectedAgent??null};});}
function addVerificationTask(project,completedTask){const existing=store.list('tasks').find(t=>t.projectId===project.id&&t.verificationForTaskId===completedTask.id);if(existing)return existing;return addTaskToProject(project.id,{title:`Verify: ${completedTask.title}`,description:`Verify the output artifact/result produced by task ${completedTask.id}.`,requiredCapabilities:['testing','verification'],risk:'low',acceptance:['Artifact exists','Files are valid','Output passes L1 verification'],assignedAgentId:null,maxAttempts:2,executor:'internal.verify-code',sequence:(completedTask.sequence??0)+0.5,dependsOn:[completedTask.id],verificationForTaskId:completedTask.id,state:'queued'});}
export async function planCommand(command,env={}){seedAgents();const basic=interpretCommand(command);let aiPlan=null;if(env?.AI?.run){try{aiPlan=await interpretWithAI(env,command);}catch{aiPlan=null;}}const objective=aiPlan?.objective??basic.objective;const capabilities=[...new Set([...(basic.capabilities??[]),...(aiPlan?.capabilities??[])])];const project=createProject({name:`Project: ${objective.slice(0,60)}`,objective,founderCommand:basic.command,requirements:aiPlan?.requirements??[]});const risk=riskLevel({codeWrite:/\b(code|coding|build|develop|program|implement)\b/i.test(command)});const approval=requiresApproval(risk)?requestApproval({action:`Execute founder command: ${command}`,risk,projectId:project.id}):null;const tasks=createPlannedTasks(project,{...(aiPlan??{}),capabilities},objective,risk);remember({type:'project_requirement',content:objective,scope:'project',scopeId:project.id,importance:'high',source:'founder-command'});if(approval)return{intent:basic,aiPlan,project,tasks,status:'awaiting_approval',approval};return executePlannedProject({project,task:tasks[0]?.task,selectedAgent:tasks[0]?.selectedAgent,env,plannedTasks:tasks});}
export async function executePlannedProject({project,task,selectedAgent,env={},approved=false,plannedTasks=null,excludedAgentIds=[]}){if(!task)return{project,status:'error',error:'No executable task was created',tasks:taskEntries(plannedTasks)};if(!dependenciesComplete(task))return{project,firstTask:task,selectedAgent,status:'blocked',reason:'dependencies_incomplete',tasks:taskEntries(plannedTasks)};if(requiresApproval(task.risk)&&!approved)return{project,firstTask:task,selectedAgent,status:'awaiting_approval',tasks:taskEntries(plannedTasks)};if(!selectedAgent){selectedAgent=task.executor==='internal.verify-code'?selectAgents(['testing','verification'])[0]:selectAgents(task.requiredCapabilities??[],null,{}).find(a=>!excludedAgentIds.includes(a.id))??null;}if(!selectedAgent)return{project,firstTask:task,status:'blocked',reason:'no_available_agent',tasks:taskEntries(plannedTasks)};updateAgent(selectedAgent.id,{state:'working',currentTaskId:task.id,heartbeatAt:now()});const working=store.put('tasks',{...task,state:'working',startedAt:now(),attempts:(task.attempts??0)+1,assignedAgentId:selectedAgent.id,id:task.id});let execution=await executeTask(working,{env,approved,agentId:selectedAgent.id});let verification=verifyResult(working,execution);let attempt=1;while(!verification.passed&&attempt<(working.maxAttempts??3)){const decision=retryDecision(working,verification,attempt);if(decision.action!=='retry')break;attempt=decision.attempt;execution=await executeTask(working,{env,retry:true,attempt,approved,agentId:selectedAgent.id,forceRestart:true});verification=verifyResult(working,execution);}const success=verification.passed;if(selectedAgent){recordAgentOutcome(selectedAgent.id,{success,taskId:working.id,verificationId:verification.id});recordAgentTaskLearning({agentId:selectedAgent.id,task:working,success,verification});}if(!success){updateAgent(selectedAgent.id,{state:'escalated',currentTaskId:null,heartbeatAt:now()});const alternate=selectAgents(working.requiredCapabilities??[],null,{}).find(a=>a.id!==selectedAgent.id&&!excludedAgentIds.includes(a.id));if(alternate){const failedTask=store.put('tasks',{...working,state:'failed',result:execution?.result??null,verificationId:verification.id,failedAgentId:selectedAgent.id,id:working.id});const replacement=store.put('tasks',{...failedTask,id:id('task'),state:'pending',assignedAgentId:alternate.id,attempts:0,dependsOn:working.dependsOn??[],title:`Reassigned: ${working.title}`,createdAt:now(),updatedAt:now()});return executePlannedProject({project,task:replacement,selectedAgent:alternate,env,approved,plannedTasks,excludedAgentIds:[...excludedAgentIds,selectedAgent.id]});}}
const status=success?'completed':'escalated';const finalTask=store.put('tasks',{...working,state:success?'completed':'failed',result:execution?.result??null,verificationId:verification.id,completedAt:success?now():undefined,id:working.id});if(success)updateAgent(selectedAgent.id,{state:'available',currentTaskId:null,heartbeatAt:now()});if(success&&!finalTask.verificationForTaskId){const verificationTask=addVerificationTask(project,finalTask);const verificationAgent=selectAgents(['testing','verification'])[0];if(verificationTask){return executePlannedProject({project,task:verificationTask,selectedAgent:verificationAgent,env,approved:true,plannedTasks:[{task:verificationTask,selectedAgent:verificationAgent}],excludedAgentIds:[]});}}
if(success){const next=(plannedTasks??[]).map(x=>store.get('tasks',x.task.id)).find(candidate=>candidate&&candidate.id!==finalTask.id&&candidate.state!=='completed'&&dependenciesComplete(candidate));if(next){const nextAgent=next.assignedAgentId?store.get('agents',next.assignedAgentId):null;return executePlannedProject({project,task:next,selectedAgent:nextAgent,env,approved,plannedTasks,excludedAgentIds:[]});}}
const projectTasks=store.list('tasks').filter(t=>t.projectId===project.id);const allDone=projectTasks.length>0&&projectTasks.every(t=>t.state==='completed');const projectState=allDone?'completed':status==='escalated'?'escalated':'active';const finalProject=store.put('projects',{...project,state:projectState,id:project.id});store.addEvent('command.completed',{projectId:project.id,taskId:finalTask.id,status:projectState});return{project:finalProject,firstTask:finalTask,selectedAgent,execution,verification,status:projectState,tasks:taskEntries(projectTasks)};}
export async function resumeApprovedCommand(approvalId,env={}){const approval=store.get('approvals',approvalId);if(!approval||!isApprovalGranted(approvalId))return{status:'awaiting_approval',approval};const project=store.get('projects',approval.projectId);const tasks=store.list('tasks').filter(t=>t.projectId===approval.projectId);const pending=tasks.filter(t=>t.state!=='completed');const task=pending.sort((a,b)=>(a.sequence??0)-(b.sequence??0))[0];const selectedAgent=task?.assignedAgentId?store.get('agents',task.assignedAgentId):selectAgents(task?.requiredCapabilities??['planning'])[0];if(!project||!task)return{status:'error',error:'Approved project/task not found'};return executePlannedProject({project,task,selectedAgent,env,approved:true,plannedTasks:tasks.map(t=>({task:t,selectedAgent:t.assignedAgentId?store.get('agents',t.assignedAgentId):null}))});}
