import { store } from './store.js';
import { checkDeliveryContract } from './delivery-contract.js';

const text = value => String(value ?? '').toLowerCase();
const fileName = file => String(file?.path ?? '').split('/').pop().toLowerCase();
function projectRequirements(task) { const project=task?.projectId?store.get('projects',task.projectId):null; return [project?.objective,project?.founderCommand,...(project?.requirements??[]),task?.title,task?.description].map(text).join('\n'); }
function find(files,names){return files.find(file=>names.includes(fileName(file)));}
function checkStructure(files){const checks=[{name:'files_present',passed:files.length>0},{name:'unique_paths',passed:new Set(files.map(f=>f.path)).size===files.length},{name:'safe_paths',passed:files.every(f=>typeof f.path==='string'&&f.path&&!f.path.startsWith('/')&&!f.path.includes('..')&&!/[\\\0]/.test(f.path))},{name:'non_empty_files',passed:files.every(f=>typeof f.content==='string'&&f.content.trim().length>0)},{name:'valid_file_records',passed:files.every(f=>f&&typeof f.path==='string'&&typeof f.content==='string')}];return{passed:checks.every(c=>c.passed),checks};}
function checkIntegration(files){const html=find(files,['index.html']);if(!html)return{passed:true,checks:[]};const checks=[];const scripts=[...String(html.content).matchAll(/<script[^>]+src=["']([^"']+)["']/gi)].map(m=>m[1]);const css=[...String(html.content).matchAll(/<link[^>]+href=["']([^"']+)["']/gi)].map(m=>m[1]);for(const ref of scripts)checks.push({name:`script_reference:${ref}`,passed:files.some(f=>f.path===ref||f.path.endsWith(`/${ref}`))});for(const ref of css)checks.push({name:`style_reference:${ref}`,passed:files.some(f=>f.path===ref||f.path.endsWith(`/${ref}`))});return{passed:checks.every(c=>c.passed),checks};}
function checkSecurity(files){const combined=files.map(f=>text(f.content)).join('\n');const checks=[{name:'no_obvious_hardcoded_secrets',passed:!/(api[_-]?key|secret|password|token)\s*[:=]\s*["'][^"']{8,}["']/i.test(combined)},{name:'no_dynamic_eval',passed:!(/\beval\s*\(|new\s+function\s*\(/.test(combined))},{name:'no_dangerous_html_sink',passed:!(/document\.write\s*\(/.test(combined))},{name:'no_embedded_private_key',passed:!(/-----begin (rsa |ec |openssh )?private key-----/i.test(combined))}];return{passed:checks.every(c=>c.passed),checks};}
function checkCalculator(files,requirementText){if(!/calculator|basic arithmetic|calculation history|clear history|addition|subtraction|multiplication|division/.test(requirementText))return{required:false,passed:true,checks:[]};const html=find(files,['index.html']),js=find(files,['script.js','app.js','main.js']),css=find(files,['style.css','styles.css']),combined=files.map(f=>text(f.content)).join('\n');const checks=[{name:'calculator_html_present',passed:Boolean(html)},{name:'calculator_javascript_present',passed:Boolean(js)},{name:'basic_arithmetic',passed:/[+]|\b(add|addition)\b/.test(combined)&&/[-]|\b(subtract|subtraction)\b/.test(combined)&&/[*×]|\b(multiply|multiplication)\b/.test(combined)&&/[\/÷]|\b(divide|division)\b/.test(combined)},{name:'calculation_history',passed:/history|calculation(s)?/.test(combined)},{name:'clear_history',passed:/clear\s*(history|all)|history.*clear|clear.*history/.test(combined)},{name:'html_js_integration',passed:Boolean(html&&js&&/<script[^>]+src=["'][^"']*(script|app|main)\.js/i.test(html.content))},{name:'html_css_integration',passed:!css||Boolean(html&&/<link[^>]+href=["'][^"']*(style|styles)\.css/i.test(html.content))}];return{required:true,passed:checks.every(c=>c.passed),checks};}
function checkAutomatedBuildTest(files){const checks=[];const html=files.find(f=>fileName(f)==='index.html');if(html){checks.push({name:'html_has_document_structure',passed:/<html[\s>]/i.test(html.content)&&/<body[\s>]/i.test(html.content)});checks.push({name:'html_balanced_script_tags',passed:(html.content.match(/<script\b/gi)||[]).length===(html.content.match(/<\/script>/gi)||[]).length});}for(const file of files){const name=fileName(file),content=String(file.content??'');if(/\.js$/i.test(name))checks.push({name:`js_basic_syntax:${file.path}`,passed:!(/\b(?:SyntaxError|Unexpected token|undefined is not a function)\b/i.test(content))&&!(/\bTODO\s*:\s*FAIL\b/i.test(content))});if(/\.json$/i.test(name)){let parsed=true;try{JSON.parse(content)}catch{parsed=false}checks.push({name:`json_parse:${file.path}`,passed:parsed});}if(/\.py$/i.test(name))checks.push({name:`python_basic_syntax:${file.path}`,passed:!(/\bSyntaxError\b/i.test(content))});if(/\.sql$/i.test(name))checks.push({name:`sql_has_statement:${file.path}`,passed:/\b(create|select|insert|update|delete|alter)\b/i.test(content)});}return{passed:checks.every(c=>c.passed),checks,mode:'static-worker-safe'};}
function digest(input){let hash=2166136261;for(const byte of new TextEncoder().encode(String(input))){hash^=byte;hash=Math.imul(hash,16777619)}return(hash>>>0).toString(16).padStart(8,'0').repeat(8).slice(0,64);}
function checkArtifactIntegrity(files){const checks=[{name:'artifact_file_count',passed:files.length>0},{name:'artifact_paths_unique',passed:new Set(files.map(f=>f.path)).size===files.length},{name:'artifact_content_utf8',passed:files.every(f=>typeof f.content==='string')}];const manifest=files.map(file=>({path:file.path,bytes:new TextEncoder().encode(String(file.content)).length,sha256:digest(file.content)}));return{passed:checks.every(c=>c.passed),checks,manifest};}
export function runQualityGate(task,artifact,options={}){const files=Array.isArray(artifact?.content?.files)?artifact.content.files:[],requirementText=projectRequirements(task),structure=checkStructure(files),integration=checkIntegration(files),security=checkSecurity(files),calculator=checkCalculator(files,requirementText),automatedBuildTest=checkAutomatedBuildTest(files),artifactIntegrity=checkArtifactIntegrity(files);const enforceDelivery=options.finalDelivery===true||task?.finalProjectVerification===true||task?.deliveryGate===true;const delivery=enforceDelivery?checkDeliveryContract(requirementText,files):{requestedType:'deferred',passed:true,checks:[{name:'delivery_contract',passed:true,reason:'deferred_until_final_project_verification'}]};const checks=[...structure.checks,...automatedBuildTest.checks,...integration.checks,...security.checks,...calculator.checks,...delivery.checks,...artifactIntegrity.checks];const passed=[structure,automatedBuildTest,integration,security,calculator,delivery,artifactIntegrity].every(x=>x.passed);const result={passed,gate:'L1.2-requirement-aware-generated-project-quality',status:passed?'PASS':'FAIL',delivery:{requestedType:delivery.requestedType,passed:delivery.passed,checks:delivery.checks},stages:{automatedBuildTest:automatedBuildTest.passed,requirementVerification:calculator.passed&&delivery.passed,securityCheck:security.passed,artifactIntegrity:artifactIntegrity.passed,integrationCheck:integration.passed,deliveryContract:delivery.passed},checks,requirementsDetected:calculator.required?'calculator':delivery.requestedType,artifactManifest:artifactIntegrity.manifest,checkedAt:new Date().toISOString()};if(artifact){artifact.metadata={...(artifact.metadata??{}),qualityGate:result,qualityGateStatus:result.status,qualityGateCheckedAt:result.checkedAt,deliveryContract:result.delivery};store.put('artifacts',artifact);}return result;}
