import { id, now } from './core.js';
import { store } from './store.js';
import { selectAgents, updateAgent } from './agents.js';

export const TASK_STATES = ['queued','assigned','working','verifying','completed','failed','blocked','cancelled'];
export function createTask({ projectId=null,title,description='',requiredCapabilities=[],risk='normal',dependsOn=[],acceptance=[],maxAttempts=3,executor='internal.plan',assignedAgentId=null,agentId=null,toolNames=[],requiredTools=[],sequence=0,...extra }) { const assigned=assignedAgentId??agentId??null; const task=store.put('tasks',{id:id('task'),projectId,title,description,requiredCapabilities,risk,dependsOn,acceptance,state:'queued',attempts:0,maxAttempts,executor,assignedAgentId:assigned,agentId:assigned,toolNames:Array.isArray(toolNames)?toolNames:[],requiredTools:Array.isArray(requiredTools)?requiredTools:[],sequence,...extra}); store.addEvent('task.created',task); return task; }
export function assignTask(taskId,agentId=null) { const task=store.get('tasks',taskId); if(!task)return null; const deps=(task.dependsOn??[]).map(x=>store.get('tasks',x)); if(deps.some(d=>d&&d.state!=='completed'))return store.put('tasks',{...task,state:'blocked',blockedReason:'Dependencies incomplete',id:task.id}); const requiredTools=Array.isArray(task.requiredTools)&&task.requiredTools.length?task.requiredTools:(Array.isArray(task.toolNames)?task.toolNames:[]); let agent=agentId?store.get('agents',agentId):(task.assignedAgentId?store.get('agents',task.assignedAgentId):selectAgents(task.requiredCapabilities,null,{requiredTools,requireAllTools:true})[0]); if(!agent){agent=selectAgents(task.requiredCapabilities,null,{requiredTools,requireAllTools:true,allowCooldownFallback:true})[0];} if(!agent)return store.put('tasks',{...task,state:'blocked',blockedReason:'No capable available agent',id:task.id}); const assigned=store.put('tasks',{...task,state:'assigned',agentId:agent.id,assignedAgentId:agent.id,assignedAt:now(),blockedReason:undefined,id:task.id}); updateAgent(agent.id,{state:'assigned',currentTaskId:task.id}); store.addEvent('task.assigned',assigned); return assigned; }
export function startTask(taskId){const task=store.get('tasks',taskId);if(!task)return null;const started=store.put('tasks',{...task,state:'working',startedAt:now(),attempts:(task.attempts??0)+1,id:task.id});if(started.agentId)updateAgent(started.agentId,{state:'working',currentTaskId:started.id});store.addEvent('task.started',started);return started;}
export function markVerifying(taskId,result={}){const task=store.get('tasks',taskId);if(!task)return null;const next=store.put('tasks',{...task,state:'verifying',result,id:task.id});if(task.agentId)updateAgent(task.agentId,{state:'verifying',currentTaskId:task.id});store.addEvent('task.verifying',next);return next;}
export function completeTask(taskId,result={}){const task=store.get('tasks',taskId);if(!task)return null;const completed=store.put('tasks',{...task,state:'completed',result,completedAt:now(),id:task.id});if(task.agentId)updateAgent(task.agentId,{state:'available',currentTaskId:null});store.addEvent('task.completed',completed);
  // A completed prerequisite must immediately release its blocked dependents.
  for (const dependent of store.list('tasks')) {
    if (dependent.state === 'blocked' && Array.isArray(dependent.dependsOn) && dependent.dependsOn.includes(taskId)) {
      assignTask(dependent.id);
    }
  }
  return completed;
}
export function failTask(taskId,error='Execution failed'){const task=store.get('tasks',taskId);if(!task)return null;const failed=store.put('tasks',{...task,state:'failed',error,failedAt:now(),id:task.id});if(task.agentId)updateAgent(task.agentId,{state:'available',currentTaskId:null});store.addEvent('task.failed',failed);return failed;}
export const listTasks=()=>store.list('tasks');